### ISSUE TITLE
train.py tran_dual.py train_triple.py The relationship and difference between the three

### ISSUE THREAD

**Issue by wq247726404** [WongKinYiu/yolov9#1]

**Comment by bailaneveryday** [comment]
I know these three files, I have compared these three train files and there is a difference in calculating the LOSS, but loading and saving the model is the same. I mean, if I use train_dual.py for training and save the weights and model with auxiliary branches, how do I remove the auxiliary branches in detect?

**Comment by ccblublu** [comment]
@WongKinYiu  After carefully comparing the three files, I noticed that there are no differences. Is the main distinction in the yaml file? What would happen if I train yolov9-e using train.py?
