### ISSUE TITLE
PGI功能和具体代码实现的对应

### ISSUE THREAD

**Issue by buxiudadilcx** [WongKinYiu/yolov9#101]
PGI部分的功能是在哪个具体的代码块里面实现的，对照了原论文附录里面的Network configurations of YOLOv9以及源码中的yolov9.yaml文件并没有发现这部分功能的代码

**Comment by YChienHung** [comment]
我也遇到了同样的问题，在对比gelan.yaml与yolov9.yaml后发现，后者多了一个分支，这应该就是PGI了，但是在训练部分并没有发现将PGI分支删除的代码，也没有在评估部分发现删除PGI分支的代码

**Comment by WongKinYiu** [comment]
Main PGI codes are in yolov9.yaml (reversible aux branch) and loss_tal_dual.py.

To remove PGI branch: https://github.com/WongKinYiu/yolov9#re-parameterization
