### ISSUE TITLE
Support for 1280 Input Size in YOLOv9 Model Architecture

### ISSUE THREAD

**Issue by MehmetOKUYAR** [WongKinYiu/yolov9#111]
Hello YOLOv9 Development Team,

I am considering using the YOLOv9 model architecture for a project of mine and am planning to set the input size to 1280x1280 for a particular application. I would like to inquire whether the model supports this input size and, if so, whether using this size has any implications for the model's accuracy or performance.

Have you had the opportunity to test the model with this input size previously?
Are there any recommendations or restrictions for using this size?
If the model supports this size, is there any expected impact on performance or accuracy?
I would greatly appreciate any guidance or suggestions you might have on this matter. Additionally, if there are any specific configurations I should be aware of when using this input size, sharing that information would be very helpful.

Thank you!

**Comment by Youho99** [comment]
Yolov9 works with 1280x1280 input size images.
But I don't know what impact this has.

I will do a test this week (I hope ahah) with a dataset (with small objetcs) with 640 and 1280 as input size images to compare this

**Comment by Youho99** [comment]
@MehmetOKUYAR 

I ran the same yolov9-e training over 100 epochs in 2 different configurations on the same dataset

On the 2 configurations, only the image size changes (1280 and 640)

My dataset is a mix between VisDrone, DGTA_VisDrone, and some background images (the dataset is more than 10k images). It is important to note that the objects in this dataset are small!

I tracked the metrics with MLflow (more information on MLflow tracking here: #87 )

In the image, we see my mAP_0.5 metric.
In salmon: yolov9-e 1280
In blue: yolov9-e 640

![image](https://github.com/WongKinYiu/yolov9/assets/44434482/09a43b6e-284b-4b8b-b150-1bf67eb51e3d)

I can therefore argue that changing the input size has a significant advantage when working with small objects!

**Comment by MehmetOKUYAR** [comment]
@Youho99 
Thank you very much for sharing your experience with us. It has truly yielded valuable results. The difference in success rate seems to be quite significant. Thanks!

**Comment by icaroryan** [comment]
@Youho99 Do you have any other tips to work with small objects other than changing the input size?

**Comment by john09282922** [comment]
Can you explain how to train using custom dataset 1280? 

Thanks,

**Comment by olddface** [comment]
> Can you explain how to train using custom dataset 1280?
> 
> Thanks,

you can override the variable "imgsz" by 1280 in train_dual.py for easier approach
