### ISSUE TITLE
full-form of "c" and "e" in yolov9 models

### ISSUE THREAD

**Issue by 0xSynapse** [WongKinYiu/yolov9#113]
We can understand that this yolov9 models are sorted according to the param-count and performance.

But what do you mean by **c** and **e** in **yolov9-c** and **yolov9-e** model names?

**Comment by ashish-roopan** [comment]
They have not mentioned that in the paper. I would be nice to know that.

**Comment by WongKinYiu** [comment]
c and e indicate compact and extended models, which are mentioned in Table 3 and Section 5.2, respectively.

**Comment by WongKinYiu** [comment]
Aux branch has additional parameters and can be removed at inference stage.
We provide re-parameterization script to get the converted model for inference.
You could download `yolov9-c-converted.pt` to see real \#params and FLOPs.

**Comment by 0xSynapse** [comment]
Thank you @WongKinYiu,
I have published a blog explaining YOLOv9 for OpenCV at LearnOpenCV's official site. 
You can give it a read [link ](https://learnopencv.com/yolov9-advancing-the-yolo-legacy/)
--- If you agree, we can add this to the YOLOv9 readme file.

**Comment by WongKinYiu** [comment]
Added to readme.

**Comment by 0xSynapse** [comment]
@WongKinYiu  I just added a PR with an updated button for the blog, as it's difficult for viewers to find.

I hope you will see it.

Thank you.
