### ISSUE TITLE
yolov9支持旋转目标检测吗？

### ISSUE THREAD

**Issue by longjiangmm** [WongKinYiu/yolov9#118]
我想用yolov9做旋转目标检测，但是感觉他没这个功能哈

**Comment by theankeshh** [comment]
PLEASE COMMENT IN ENGLISH. WE WOULD BE HAPPY TO LET UP YOUR EXCPECTATIONS AS PER OUR PROJECT

**Comment by Kayzwer** [comment]
> PLEASE COMMENT IN ENGLISH. WE WOULD BE HAPPY TO LET UP YOUR EXCPECTATIONS AS PER OUR PROJECT

obb with yolov9

**Comment by Kayzwer** [comment]
> 我想用yolov9做旋转目标检测，但是感觉他没这个功能哈

可能可以从ultralytics那里拿一些代码用一用，那边有OBB的head和loss function.

**Comment by longjiangmm** [comment]
> PLEASE COMMENT IN ENGLISH. WE WOULD BE HAPPY TO LET UP YOUR EXCPECTATIONS AS PER OUR PROJECT

Does yolov9 not support rotating object detection? How to get his support?

**Comment by longjiangmm** [comment]
> > 我想用yolov9做旋转目标检测，但是感觉他没这个功能哈
> 
> 可能可以从ultralytics那里拿一些代码用一用，那边有OBB的head和loss function.

主要是没空弄他，想当一把伸手党

**Comment by Kayzwer** [comment]
> > > 我想用yolov9做旋转目标检测，但是感觉他没这个功能哈
> > 
> > 可能可以从ultralytics那里拿一些代码用一用，那边有OBB的head和loss function.
> 
> 主要是没空弄他，想当一把伸手党

我有空会弄一弄

**Comment by longjiangmm** [comment]
> > > > 我想用yolov9做旋转目标检测，但是感觉他没这个功能哈
> > > 
> > > 
> > > 可能可以从ultralytics那里拿一些代码用一用，那边有OBB的head和loss function.
> > 
> > 
> > 主要是没空弄他，想当一把伸手党
> 
> 我有空会弄一弄

太好了，很期待哈

**Comment by Kayzwer** [comment]
> > > > > 我想用yolov9做旋转目标检测，但是感觉他没这个功能哈
> > > > 
> > > > 
> > > > 可能可以从ultralytics那里拿一些代码用一用，那边有OBB的head和loss function.
> > > 
> > > 
> > > 主要是没空弄他，想当一把伸手党
> > 
> > 我有空会弄一弄
> 
> 太好了，很期待哈

ultralytics现在有yolov9了，你尝试修改下.yaml好像就行了

**Comment by longjiangmm** [comment]
> ultralytics

有了吗？我前几天还只看到yolov8的哈!

**Comment by Kayzwer** [comment]
> > ultralytics
> 
> 有了吗？我前几天还只看到yolov8的哈!

有了有了，git pull一下就可以了

**Comment by WongKinYiu** [comment]
Temporally, you could use https://github.com/WongKinYiu/yolov9/tree/yolov9u
