### ISSUE TITLE
Segment, classify, panoptic modules

### ISSUE THREAD

**Issue by Doan-IT** [WongKinYiu/yolov9#12]
Thank you for your hard work. I've been following you since the release of yolov7.
In this project, I don't see the results and benchmarks of segment, classify, panoptic modules. 
Can you provide more information about them?

**Comment by WongKinYiu** [comment]
Classify code is from yolov5, I have not examine it.
Segment and Panoptic are parts of code of [teaser](https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#teaser), full code will be released in the future.

**Comment by PHaiJun** [comment]
Wish Segment experiments!!!!!!!!!!

**Comment by yjx12345** [comment]
Update the segmentation model ASAP. Thanks
