### ISSUE TITLE
Any plan of yolov9_n?

### ISSUE THREAD

**Issue by qiangxinglin** [WongKinYiu/yolov9#120]
Thank you for the bravo project!  
Is there any plan of developing a nano-version of the yolov9? Then the mobile edge devices can take the benifit from it.

**Comment by NeuralAIM** [comment]
| Model | Test Size | AP<sup>val</sup> | AP<sub>50</sub><sup>val</sup> | AP<sub>75</sub><sup>val</sup> | Param. | FLOPs |
| :-- | :-: | :-: | :-: | :-: | :-: | :-: |
[**YOLOv9-N (dev)**]() | 640 | **38.3%** | **53.1%** | **41.3%** | **2.0M** | **7.7G** |

- 9660d12
