### ISSUE TITLE
Why don't the parameters match?

### ISSUE THREAD

**Issue by zrg0712** [WongKinYiu/yolov9#122]
yolov9-c The table shows 25.3M, but myself tested results is 51.3M use thop packages

**Comment by WongKinYiu** [comment]
Please use yolov9-c-converted.pt for testing.

51.3M is model for training, 25.3M is model for inference.
You could get model for inference using https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization.

**Comment by lifeternity** [comment]
how can I use the reparam script to rebuild the new .pt training on other datasets,could you please tell me that?

**Comment by WongKinYiu** [comment]
Follow `yolov9-c.yaml` and `gelan-c.yaml` to create your model for inference.
And modify the `.pt` and `.yaml` in the script.
If you design your own architecture, please check if the idx mapping is correct.

**Comment by wgqhandsome** [comment]
> yolov9-c The table shows 25.3M, but myself tested results is 51.3M use thop packages

我也遇到了这个问题，请问你解决了吗

**Comment by naruto123sdo** [comment]
> Please use yolov9-c-converted.pt for testing.
> 
> 51.3M is model for training, 25.3M is model for inference. You could get model for inference using https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization.

Hi @WongKinYiu, what does re-parameterization do exactly? Is it mainly used to remove the auxiliary branch so that the correct latency and model size can be measured?
