### ISSUE TITLE
environment 

### ISSUE THREAD

**Issue by john09282922** [WongKinYiu/yolov9#129]
python, any other version, plz

**Comment by Akshaykushawaha** [comment]
Can you please elaborate on your issue?

**Comment by Akshaykushawaha** [comment]
You can check this: [https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#installation](url)

And for installing all the dependencies, you can use:
`pip install -r requirements.txt`

If you want to use your GPU as well, then you would also need to install CUDA and cuDNN.
Link for CUDA: [https://developer.nvidia.com/cuda-downloads](url)

Link for cuDNN:
Linux [https://docs.nvidia.com/deeplearning/cudnn/installation/linux.html](url) 
Windows [https://docs.nvidia.com/deeplearning/cudnn/installation/windows.html](url) 

Please correct me if I misunderstood your question.

**Comment by WongKinYiu** [comment]
docker
https://github.com/WongKinYiu/yolov9/tree/main?tab=readme-ov-file#installation

colab, conda, docker, ...
https://github.com/WongKinYiu/yolov9/tree/main?tab=readme-ov-file#useful-links
