### ISSUE TITLE
YOLOv9 with End2End ( Efficient NMS)

### ISSUE THREAD

**Issue by levipereira** [WongKinYiu/yolov9#130]
Thank you for your wonderful work!

**YOLOv9  with End2End ( Efficient NMS)**

I've created a forked repository from the original, adding End-to-End support for ONNX export. The changes can be found in [export.py](https://github.com/levipereira/yolov9/blob/main/export.py) and [models/experimental.py](https://github.com/levipereira/yolov9/blob/main/models/experimental.py).  Both files remain fully compatible with all current export operations.  
Check it out at [https://github.com/levipereira/yolov9](https://github.com/levipereira/yolov9)

- **Support for End-to-End ONNX Export**: Added support for end-to-end ONNX export in `export.py` and `models/experimental.py`.

- **Model Compatibility**: This functionality currently works only with the `yolov9-c.pt` and `yolov9-e.pt` models (`DetectionModel`); other models are not yet supported.

- **Configuration Variables**: Use the following flags to configure the model:
  - `--include onnx_end2end`: Enabled export End2End
  - `--simplify`: ONNX/ONNX END2END: Simplify model.
  - `--topk-all`: ONNX END2END/TF.js NMS: Top-k for all classes to keep (default: 100).
  - `--iou-thres`: ONNX END2END/TF.js NMS: IoU threshold (default: 0.45).
  - `--conf-thres`: ONNX END2END/TF.js NMS: Confidence threshold (default: 0.25).

 

Example:

``` shell
$ python3 export.py --weights ./yolov9-c.pt --imgsz 640 --simplify --include onnx_end2end

export: data=data/coco.yaml, weights=['./yolov9-c.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx_end2end']
YOLOv5 🚀 v0.1-27-g86b0667 Python-3.8.10 torch-1.14.0a0+44dac51 CPU

Fusing layers...
Model summary: 604 layers, 50880768 parameters, 0 gradients, 237.6 GFLOPs

PyTorch: starting from ./yolov9-c.pt with output shape (1, 84, 8400) (98.4 MB)

ONNX END2END: starting export with onnx 1.13.0...
/yolov9/models/experimental.py:102: FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in 1.14. Please note 'g.op()' is to be removed from torch.Graph. Please open a GitHub issue if you need this functionality..
  out = g.op("TRT::EfficientNMS_TRT",
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
========== Diagnostic Run torch.onnx.export version 1.14.0a0+44dac51 ===========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 4 WARNING 0 ERROR ========================
4 WARNING were not printed due to the log level.


Starting to simplify ONNX...
ONNX export success, saved as ./yolov9-c_end2end.onnx
ONNX END2END: export success ✅ 11.5s, saved as ./yolov9-c_end2end.onnx (129.3 MB)

Export complete (13.6s)
Results saved to /yolov9/experiments/models
Visualize:       https://netron.app

```

**Comment by levipereira** [comment]
**YOLOv9  with End2End ( Efficient NMS)**

I've created a forked repository from the original, adding End-to-End support for ONNX export. The changes can be found in [export.py](https://github.com/levipereira/yolov9/blob/main/export.py) and [models/experimental.py](https://github.com/levipereira/yolov9/blob/main/models/experimental.py).  Both files remain fully compatible with all current export operations.  
Check it out at [https://github.com/levipereira/yolov9](https://github.com/levipereira/yolov9)


- **Support for End-to-End ONNX Export**: Added support for end-to-end ONNX export in `export.py` and `models/experimental.py`.

- **Model Compatibility**: This functionality currently works only with the `yolov9-c.pt` and `yolov9-e.pt` models (`DetectionModel`); other models are not yet supported.

- **Configuration Variables**: Use the following flags to configure the model:
  - `--include onnx_end2end`: Enabled export End2End
  - `--simplify`: ONNX/ONNX END2END: Simplify model.
  - `--topk-all`: ONNX END2END/TF.js NMS: Top-k for all classes to keep (default: 100).
  - `--iou-thres`: ONNX END2END/TF.js NMS: IoU threshold (default: 0.45).
  - `--conf-thres`: ONNX END2END/TF.js NMS: Confidence threshold (default: 0.25).

 

Example:

``` shell
$ python3 export.py --weights ./yolov9-c.pt --imgsz 640 --simplify --include onnx_end2end

export: data=data/coco.yaml, weights=['./yolov9-c.pt'], imgsz=[640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx_end2end']
YOLOv5 🚀 v0.1-27-g86b0667 Python-3.8.10 torch-1.14.0a0+44dac51 CPU

Fusing layers...
Model summary: 604 layers, 50880768 parameters, 0 gradients, 237.6 GFLOPs

PyTorch: starting from ./yolov9-c.pt with output shape (1, 84, 8400) (98.4 MB)

ONNX END2END: starting export with onnx 1.13.0...
/yolov9/models/experimental.py:102: FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in 1.14. Please note 'g.op()' is to be removed from torch.Graph. Please open a GitHub issue if you need this functionality..
  out = g.op("TRT::EfficientNMS_TRT",
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W shape_type_inference.cpp:1913] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
========== Diagnostic Run torch.onnx.export version 1.14.0a0+44dac51 ===========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 4 WARNING 0 ERROR ========================
4 WARNING were not printed due to the log level.


Starting to simplify ONNX...
ONNX export success, saved as ./yolov9-c_end2end.onnx
ONNX END2END: export success ✅ 11.5s, saved as ./yolov9-c_end2end.onnx (129.3 MB)

Export complete (13.6s)
Results saved to /yolov9/experiments/models
Visualize:       https://netron.app

```

**Comment by WongKinYiu** [comment]
Added to readme.

**Comment by levipereira** [comment]
Thanks.  Fixed the issue was set output[1] as the prediction for the main branch instead of output[0].
https://github.com/levipereira/yolov9/commit/20f921ff4ab8738f6aef24fa4ef1977a44ed258d

**Comment by levipereira** [comment]
@WongKinYiu   
I've made some changes and tested them, and so far, no issues have been found. However, I need your support. I've noticed that in YOLOv7 models with more than one class, we have to multiply `obj_conf * cls_conf`. This multiplication is missing in the current code.


Could you please review and advise ?

I want replace this code:
https://github.com/levipereira/yolov9/blob/main/models/experimental.py#L141
```python
bboxes_x = output[..., 0:1]
bboxes_y = output[..., 1:2]
bboxes_w = output[..., 2:3]
bboxes_h = output[..., 3:4]
bboxes = torch.cat([bboxes_x, bboxes_y, bboxes_w, bboxes_h], dim=-1)
bboxes = bboxes.unsqueeze(2)  # [n_batch, n_bboxes, 4] -> [n_batch, n_bboxes, 1, 4]
obj_conf = output[..., 4:]
scores = obj_conf
```

with this code:

https://github.com/WongKinYiu/yolov7/blob/main/models/experimental.py#L211

```python
bboxes = output[:, :, :4]
conf = output[:, :, 4:5]
scores = output[:, :, 5:]

if self.n_classes == 1:
    scores = conf  # for models with one class, cls_loss is 0 and cls_conf is always 0.5,
                  # so there is no need to multiply.
else:
    scores *= conf  # conf = obj_conf * cls_conf
```

**Comment by levipereira** [comment]
@WongKinYiu  

I haven't implemented the Detect() Layer in YOLOv9 yet, and so far and I haven't encountered any issues. 

What is your recommendation regarding the usage of the Detect() Layer in YOLOv9 for ONNX export ? 

When set `model.model[-1].export = False` in YOLOv9, the [output](https://github.com/levipereira/yolov9/blob/main/models/experimental.py#L134) type is `<class 'tuple'>`, when set it to `True` , the output type is `<class 'torch.Tensor'>` or `<class 'list'>`.

Considering this, if I enable the Detect() Layer, I need to implement it.

For more context, please refer to:

[Issue #343](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658021043)

[Implementation reference](https://github.com/WongKinYiu/yolov7/blob/a207844b1ce82d204ab36d87d496728d3d2348e7/export.py#L67) (setting Detect() layer grid export)

Your insights on how to proceed would be highly appreciated.

**Comment by laugh12321** [comment]
Hello everyone!

I would like to introduce my open-source project - [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO), a tool for deploying YOLO Series (Support YOLOv9) with Efficient NMS in TensorRT. 

## Key Features

- Supports FLOAT32, FLOAT16 ONNX export, and TensorRT inference
- Supports YOLOv5, YOLOv8, YOLOv9, PP-YOLOE, and PP-YOLOE+
- Integrates EfficientNMS TensorRT plugin for accelerated post-processing
- Utilizes CUDA kernel functions to accelerate preprocess
- Supports C++ and Python inference

## Perfomance
Perfomance Test using GPU RTX 2080Ti 22GB on AMD Ryzen 7 5700X 8-Core/ 128GB RAM.

Model Performance Evaluation using TensorRT engine using [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO).

All models were deployed using FP16, BatchSize 4 and size 640. 

### YOLOv9 Series

This includes the YOLOv9-C, YOLOv9-E, YOLOv9-C-Converted, YOLOv9-E-Converted, GELAN-C and GELAN-E.

| YOLOv9-C           | YOLOv9-E           | YOLOv9-C-Converted | YOLOv9-E-Converted | GELAN-C | GELAN-E |
| ------------------ | ------------------ | ------------------ | ------------------ | ------- | ------- |
| Average Latency: `36.615ms` | Average Latency: `59.736ms` | Average Latency: `19.689ms` | Average Latency: `53.144ms` | Average Latency: `19.557ms` | Average Latency: `53.575ms` |

### YOLOv8 Series

This includes the YOLOv8n, YOLOv8s, YOLOv8m, YOLOv8l and YOLOv8x.

| YOLOv8n           | YOLOv8s          | YOLOv8m | YOLOv8l | YOLOv8x |
| ------------------ | ------------------ | ------------------ | ------------------ | ------- |
| Average Latency: `10.289ms` | Average Latency: `12.459ms` | Average Latency: `18.514ms` | Average Latency: `24.926ms` | Average Latency: `34.587ms` |

**Comment by radandreicristian** [comment]
Hey @levipereira, first of all thanks for this work!

The warning in the ONNX export step results in a run-time error when trying to do the inference.

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from gelan-c-end2end.onnx failed:Fatal error: TRT:EfficientNMS_TRT(-1) is not a registered function/op
```

Any idea what could cause this? I could provide more code/context if needed.

**Comment by levipereira** [comment]
# Use the official NVIDIA PyTorch image as the base image
FROM nvcr.io/nvidia/pytorch:23.02-py3

# Update and install required dependencies
RUN apt-get update \
    && apt-get install -y zip htop screen libgl1-mesa-glx vim libfreetype6-dev graphviz  \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install necessary Python packages
RUN pip install --upgrade pip \
    && pip install seaborn \
                   thop \
                   markdown-it-py==2.2.0 \
                   onnx-simplifier==0.4.35 \
                   onnxsim==0.4.35 \
                   onnxruntime==1.16.3 \
                   ujson==5.9.0 \
                   pycocotools==2.0.7 \
                   virtualenv \
                   widgetsnbextension==4.0.9 \
    && pip install --no-cache-dir --force-reinstall pillow==9.5.0


RUN mkdir -p /opt/nvidia_trex

# Create and activate a virtual environment Clone TensorRT repository and install trt-engine-explorer (trex)
RUN cd /opt/nvidia_trex/ \
    && python3 -m virtualenv env_trex \
    && /bin/bash -c "source env_trex/bin/activate && pip install Werkzeug==2.2.2 graphviz==0.20.1" \
    && cd /opt/nvidia_trex/ \
    && git clone https://github.com/NVIDIA/TensorRT.git \
    && cd TensorRT \
    && git checkout release/8.6 \
    && cd tools/experimental/trt-engine-explorer \
    && /bin/bash -c "source /opt/nvidia_trex/env_trex/bin/activate && pip install -e ." \
    && /bin/bash -c "source /opt/nvidia_trex/env_trex/bin/activate && jupyter nbextension enable widgetsnbextension --user --py"


## Deploy yolov7
RUN cd / \
    && git clone https://github.com/levipereira/yolov9.git

WORKDIR /yolov9

**Comment by levipereira** [comment]
> The warning in the ONNX export step results in a run-time error when trying to do the inference.
> Any idea what could cause this? I could provide more code/context if needed.

Inference with an end-to-end model using YOLOv9 source code is not supported due to lack of implementation. 
Instead, utilize the [triton-server](https://github.com/levipereira/triton-server-yolo-v7-v9/) repository for this purpose.
A triton-client repository will be released, enabling users to perform inference on the triton-server.

**Comment by laugh12321** [comment]
@berkgungor Hi, You can try [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO)， which also supports exporting onnx with Efficient NMS and does not require reparameterizing the finetuned pt.

**Comment by levipereira** [comment]
@mdciri @radandreicristian  The primary purpose of employing End2End is to utilize ONNX models on TensorRT. If you choose not to use TensorRT, you should proceed with the standard ONNX export process.

**Comment by gl94** [comment]
> Hi, do we have to reparametrize the finetuned pt file before exporting to onnx format? Because when i perform the reparametrize python code it throws error like "AttributeError: 'DetectionModel' object has no attribute 'nc'" .
you could 


> Hi, do we have to reparametrize the finetuned pt file before exporting to onnx format? Because when i perform the reparametrize python code it throws error like "AttributeError: 'DetectionModel' object has no attribute 'nc'" .
When you encounter the "AttributeError: 'DetectionModel' object has no attribute 'nc'" error, you can manually change "model.nc" to "your num of classes"（in my case,model.nc=4).And also in "glan-c.yaml" line 4: change "nc: 80" to "nc: your nc",line 79: change
"[[15, 18, 21], 1, DDetect, [nc]]" to "[[15, 18, 21], 1, DDetect, [your nc]]"

**Comment by PrinceP** [comment]
Hi all, 
https://github.com/PrinceP/tensorrt-cpp-for-onnx

Here's the dynamic batch version for yolov9 inference in tensorrt in C++ using the @levipereira work for dynamic support.

Any batchsize with any image size is supported here. Reference code for batching data is also present.

**Comment by mdciri** [comment]
@levipereira yes, for your implementation the End2End is to use the ONNX model on TensorRT. Anyway, I would like to convert my model to ONNX (with NMS) that works on ONNXRUNTIME. 

At the moment, the export to ONNX does not take into consideration the NMS.

**Comment by gl94** [comment]
> @gl94 i already changed class numbers in yaml, nothing has changed. Same error.
> 
> @levipereira i exported the model to onnx just using --include onnx without specifying end2end and then converted to tensorRT engine. Works fine. I also did not reparametrize since it threw error.

You might should also make the same change in the reparametrize python code. From "model.nc = ckpt['model'].nc" to "model.nc = your nc"
