### ISSUE TITLE
What's the difference between yolov9-c-converted.pt and gelan-c.pt?

### ISSUE THREAD

**Issue by zrg0712** [WongKinYiu/yolov9#131]
as shown in the question, and is gelan an inference version of yolov9?

**Comment by WongKinYiu** [comment]
`yolov9-c-converted.pt` remove aux branch of `yolov9-c.pt` for inference.
And yes, gelan is inference version, we use it to create converted yolov9.

https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization

**Comment by zrg0712** [comment]
but i got incorrect result using yolov9-c-converted.pt to detect...

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#inference

I have tested them and all of models get normal results.
You could try this.
