### ISSUE TITLE
There is a problem of `'list' object has no attribute 'device'` in `detect.py` of revised yolov9-c.pt model.

### ISSUE THREAD

**Issue by mpj1234** [WongKinYiu/yolov9#133]
parameter:
![image](https://github.com/WongKinYiu/yolov9/assets/78143172/5d2bab5b-958d-4a3c-a787-e231320cac59)
bug:
![image](https://github.com/WongKinYiu/yolov9/assets/78143172/b1ea20f5-f271-41f6-ba8f-cfade35908e0)
This problem has been submitted to pr for repair.

**Comment by WongKinYiu** [comment]
The pr is wrong.

prediction[0][0] is output of aux branch, you need to get prediction[0][1].

https://github.com/WongKinYiu/yolov9/issues/11#issuecomment-1960610186
