### ISSUE TITLE
yaml file of yolov9-S

### ISSUE THREAD

**Issue by Stephen-Hao** [WongKinYiu/yolov9#140]
Thank you for your yolov9 project, Can you upload the yaml file of yolov9-S?

**Comment by yanshuangying888** [comment]
Similarly, I would like to thank the blogger again for his YOLOv9 project. I also hope that the blogger can upload relevant pre-training.pt files about YOLOv9, such as yolov9-S, yolov9-M, GELAN-S, GELAN-M and other files mentioned in the blog. Finally, I would like to thank the blogger very much for all that he has done.

**Comment by mkrupczak3** [comment]
#3

**Comment by WongKinYiu** [comment]
yolov9-s is released.
