### ISSUE TITLE
How to inference a onnx yolov9 model?

### ISSUE THREAD

**Issue by KyriakosChris** [WongKinYiu/yolov9#141]
I found how to inference a trt yolov9 model using this detect function:

    def detect(self, bgr_img):   
        ## Padded resize
        h, w, _ = bgr_img.shape
        scale = min(self.imgsz[0]/w, self.imgsz[1]/h)
        inp = np.zeros((self.imgsz[1], self.imgsz[0], 3), dtype = np.float32)
        nh = int(scale * h)
        nw = int(scale * w)
        inp[: nh, :nw, :] = cv2.resize(cv2.cvtColor(bgr_img, cv2.COLOR_BGR2RGB), (nw, nh))
        inp = inp.astype('float32') / 255.0  # 0 - 255 to 0.0 - 1.0
        inp = np.expand_dims(inp.transpose(2, 0, 1), 0)

        ## Inference
        t1 = time.time()
        num_detection, nmsed_bboxes, nmsed_scores, nmsed_classes = self.model.run(inp)
        t2 = time.time()

        ## Apply NMS
        num_detection = num_detection[0][0]
        nmsed_bboxes  = nmsed_bboxes[0]
        nmsed_scores  = nmsed_scores[0]
        nmsed_classes  = nmsed_classes[0]
        print('Detected {} object(s)'.format(num_detection))
        # Rescale boxes from img_size to im0 size
        _, _, height, width = inp.shape
        h, w, _ = bgr_img.shape
        nmsed_bboxes[:, 0] /= scale
        nmsed_bboxes[:, 1] /= scale
        nmsed_bboxes[:, 2] /= scale
        nmsed_bboxes[:, 3] /= scale
        visualize_img = bgr_img.copy()
        for ix in range(num_detection):       # x1, y1, x2, y2 in pixel format
            cls = int(nmsed_classes[ix])
            label = '%s %.2f' % (self.names[cls], nmsed_scores[ix])
            x1, y1, x2, y2 = nmsed_bboxes[ix]

            cv2.rectangle(visualize_img, (int(x1), int(y1)), (int(x2), int(y2)), self.colors[int(cls)], 2)
            cv2.putText(visualize_img, label, (int(x1), int(y1-10)), cv2.FONT_HERSHEY_SIMPLEX, 1, self.colors[int(cls)], 2, cv2.LINE_AA)

        cv2.imwrite('result.jpg', visualize_img)
        return `visualize_img`

But I can't find out how to do the same for an ONNX model. Has someone already made something like this, or should I do it and post it? Thank you.

**Comment by jdiaz97** [comment]
I have an example in Julia

https://github.com/jdiaz97/yolov9-in-julia/

Applying NMS is needed

**Comment by WongKinYiu** [comment]
More ONNX examples: https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#useful-links

Added Julia example to readme.

**Comment by yxl502** [comment]
https://zhuanlan.zhihu.com/p/683979999

**Comment by KyriakosChris** [comment]
@yxl502 @WongKinYiu 
Thank you!!! One small issue, during your preprocess you resize your image, and you lose some important information. This make the model to have worse accuracy. I created a class that can handle onnx  yolov7,yolov9 and rt-Detr, with a letterbox, now your preprocess. It works fine for me, feel free to use it.


`class TargetDetectorOnnx:

    def __init__(self, args):
        # init constructor for object detection using onnx.
        self.args = args
        self.cuda = args.cuda
        self.model = os.path.abspath(os.path.join(os.getcwd(), args.model))
        self.providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if self.cuda else ['CPUExecutionProvider']
        self.session = ort.InferenceSession(self.model, providers=self.providers)
        self.model_inputs = self.session.get_inputs()
        self.input_names = [self.model_inputs[i].name for i in range(len(self.model_inputs))]
        self.input_shape = self.model_inputs[0].shape
        self.model_output = self.session.get_outputs()
        self.output_names = [self.model_output[i].name for i in range(len(self.model_output))]
        self.__read_classes()

        # assign a unique color for each class to avoid confusion at inference time
        self.colorList = np.random.uniform(low = 0, high = 255, size = (len(self.classesList), 3))

        if len(self.args.target_classes) == 0:
            print("[utils][TargetDetectorOnnx]:: No target was specified.")
            self.target_classes = [t.upper() for t in self.classesList]
        else:
            print("[utils][TargetDetectorOnnx]:: " + str(len(self.args.target_classes)) + " target(s) specified: " + str(self.args.target_classes))
            self.target_classes = [t.upper() for t in self.args.target_classes]
        
    def __read_classes(self):
        with open(self.args.classes, 'r') as f:
            self.classesList = f.read().splitlines()
    
    def letterbox(self, im, new_shape, color=(114, 114, 114), auto=True, scaleup=True, stride=32):
        # implementation of function letterbox, that resizes an input image, to a new shape while preserving its aspect ratio.
        shape = im.shape[:2]
        if isinstance(new_shape, int):
            new_shape = (new_shape, new_shape)

        r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
        if not scaleup:
            r = min(r, 1.0)

        new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
        dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]
        if auto:
            dw, dh = np.mod(dw, stride), np.mod(dh, stride)

        dw /= 2
        dh /= 2

        if shape[::-1] != new_unpad:
            im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
        top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
        left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
        im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)
        return im, r, (dw, dh)
    
    def yolov7(self,predictions):
        boxes = []
        class_ids = []
        scores = []
        if (predictions.shape[1] == 0):
            return np.array(boxes),np.array(class_ids),np.array(scores)  
            
        for i in range(predictions.shape[1]) :
            score =  predictions[6, i]
            scores.append(score)
            box = predictions[1:5, i]
            class_id = round(predictions[5, i])
            boxes.append(box)
            class_ids.append(class_id)

        return np.array(self.xyxy2xywh(boxes)),np.array(class_ids),np.array(scores)
    
    def yolov9(self,predictions):
        boxes = []
        class_ids = []
        scores = []
        scores = np.max(predictions[:, 4:], axis=1)
        predictions = predictions[scores > self.args.conf_thres, :]
        scores = scores[scores > self.args.conf_thres]
        class_ids = np.argmax(predictions[:, 4:], axis=1)

        # Rescale box
        boxes = predictions[:, :4]
        return np.array(boxes),np.array(class_ids),np.array(scores)

    def xyxy2xywh(self,x):
        # Convert bounding box (x1, y1, x2, y2) to bounding box (x, y, w, h)
        x = np.array(x) 
        y = np.copy(x)
        y[..., 0] = (x[..., 0] + x[..., 2]) / 2  # x
        y[..., 1] = (x[..., 1] + x[..., 3]) / 2  # y
        y[..., 2] = x[..., 2] - x[..., 0]  # w
        y[..., 3] = x[..., 3] - x[..., 1]  # h
        return y
    
    @measure_avg_exec_time("TargetDetectorOnnx")
    def update(self, frame):
        # function update detects objects and returns the class id, confidence score and bounding box coordinates
        classIds, confidences, bboxs = [], [], []
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        imageframe, ratio, dwdh = self.letterbox(frame, self.args.imgsz, auto=False)
        imageframe = np.transpose(imageframe, (2, 0, 1))
        imageframe = np.expand_dims(imageframe, 0)
        imageframe = np.ascontiguousarray(imageframe)
        im = imageframe.astype(np.float32)
        im /= 255
        if 'yolo' in self.args.model :
                outputs = self.session.run(self.output_names, {self.input_names[0]: im})[0]
                
                if 'yolov7' in self.args.model :
                    predictions = outputs.T
                    boxes,classIds,confidences = self.yolov7(predictions)
                if 'yolov9' in self.args.model :
                    predictions = np.squeeze(outputs).T
                    boxes,classIds,confidences = self.yolov9(predictions)
                if len(boxes) == 0 :
                    return np.array(classIds), np.array(confidences), np.array(boxes)

                for b in boxes.copy():
                    b = np.array([b[0]-b[2]/2, b[1]-b[3]/2, (b[2]), (b[3])])
                    b -= np.array([dwdh[0], dwdh[1], 0, 0])
                    b /= ratio
                    b = b.round().astype(np.int32).tolist()
                    bboxs.append(b)
                if 'yolov9' in self.args.model :
                    indices = cv2.dnn.NMSBoxes(bboxs, confidences, score_threshold=self.args.trt_nms_conf_thres, nms_threshold=self.args.iou_thres)
                    classIds = np.array(classIds)
                    confidences = np.array(confidences)
                    bboxs = np.array(bboxs)
                    return np.array(classIds[indices]), np.array(confidences[indices]), np.array(bboxs[indices])
                
                return np.array(classIds), np.array(confidences), np.array(bboxs)
        

        # Use the RT-DETR model: 
        if 'RT-DETR' in self.args.model : 
            size = np.array([[self.args.imgsz, self.args.imgsz]], dtype=np.int64)
            output = self.session.run(
                output_names=None,
                input_feed={'images': im, "orig_target_sizes": size}
            )        
            labels, boxes, scores = output
            confidences = scores[0]
            classIds = labels[0][confidences > self.args.conf_thres]
            box = boxes[0][confidences > self.args.conf_thres]
            confidences = [round(float(x),2) for x in confidences]
            classIds = [int(x) for x in classIds]
            for b in box.copy():
                b = np.array([b[0], b[1], (b[2]-b[0]), (b[3]-b[1])])
                b -= np.array([dwdh[0], dwdh[1], 0, 0])
                b /= ratio
                b = b.round().astype(np.int32).tolist()
                
                bboxs.append(b)
        if self.args.test_metadata:
            file = open("metadata_json_detect.txt", 'a')
            for box in bboxs:
                tc_x = int(box[0] + box[2]/2)
                tc_y = int(box[1] + box[3]/2)
                file.write(f'{tc_x},{tc_y}\n') 
            file.close()

        return np.array(classIds), np.array(confidences), np.array(bboxs)
    
    @measure_avg_exec_time("TargetDetectorOnnx")
    def draw_bb(self, frame, classIds, confidences, bboxs):

        # if there was at least one object detected in the current frame
        # draw a bounding box around it with the details of its class
        # and the correspodning confidence
        
        if len(classIds) > 0:
            
            for classId, confidence, bbox in zip(classIds.flatten(), confidences.flatten(), bboxs):
                
                # There seems to be an issue with the ssd_mobilenet implementation w.r.t. yielding back
                # classIds above 80, which is impossible given that we used the coco dataset consisting of 80 classes
                # yolo does not suffer from this
                if classId < len(self.classesList) and self.classesList[classId].upper() in  self.target_classes:
                
                    # unpack bb to get its x.y coordinates as well as its width and height
                    x, y, w, h = bbox
                    # print(f"x:{x}, y:{y}, w:{w},h:{h}")
                    classLabel = self.classesList[classId]
                    classColor = [int(c) for c in self.colorList[classId]]

                    # display detected class and its corresponding confidence
                    displayText = "{}:{:.2f}".format(classLabel, confidence)
                    # cv2.rectangle(frame, bbox[:2], bbox[2:], color = classColor, thickness=1)
                    cv2.rectangle(frame, (x,y), (x+w, y+h), color = classColor, thickness = 1)

                    # display class/confidence details at the top left corner of the bb
                    cv2.putText(frame, displayText, (x, y - 10), cv2.FONT_HERSHEY_PLAIN, 1, classColor, 2)

                    # make 4 corners of the bb thick (this affects the FPS and it's not essential)
                    lineWidth = min(int(w * 0.2), int(h * 0.2))
                    thick = 3

                    cv2.line(frame, (x, y), (x + lineWidth, y), classColor, thickness = thick)
                    cv2.line(frame, (x, y), (x, y + lineWidth), classColor, thickness = thick)

                    cv2.line(frame, (x + w, y), (x + w - lineWidth, y), classColor, thickness = thick)
                    cv2.line(frame, (x + w, y), (x + w, y + lineWidth), classColor, thickness = thick)

                    cv2.line(frame, (x, y + h), (x + lineWidth, y + h), classColor, thickness = thick)
                    cv2.line(frame, (x, y + h), (x, y + h - lineWidth), classColor, thickness = thick)

                    cv2.line(frame, (x + w, y + h), (x + w - lineWidth, y + h), classColor, thickness = thick)
                    cv2.line(frame, (x + w, y + h), (x + w, y + h - lineWidth), classColor, thickness = thick)
                   
        return frame`
