### ISSUE TITLE
The error occurs while modifying the architecture of the models: depth and width

### ISSUE THREAD

**Issue by Juosir14** [WongKinYiu/yolov9#155]
Hi, kind of a newbie here.

How could I change the size of the model? 

I am assuming, by modifying **depth** and **width** in the .yaml files. Unfortunately, it does not work. For example, I am trying to change the width and/or depth of the **gelan-e.yaml**, but most of the time (found out that while depth is 0.8 and width is 1, the error does not occur, but the model size does not change) I receive similar errors to this:

_RuntimeError: stack expects each tensor to be equal size, but got [1, 64, 128, 128] at entry 0 and [1, 40, 128, 128] at entry 5_

For some reason, the **gelan-c** model does respond to the changes of gelan-c.yaml, but only differs on parameters not quantity of layers (tried different width and depth).

Any advice would be appreciated, thank You!

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/6#issuecomment-1959187480
