### ISSUE TITLE
mac - yolov9 - why epoch02 is so slow？m2芯片适配

### ISSUE THREAD

**Issue by kagura0108** [WongKinYiu/yolov9#169]
I am training YOLOV9 on a Mac M2 chip. The first epoch took 7 minutes, but the second epoch took 2 hours. Why is there such a big difference in training time between the two epochs?

my code

```
# DDP mode
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        print("MPS not available because the current PyTorch install was not "
              "built with MPS enabled.")
    else:
        print("MPS not available because the current MacOS version is not 12.3+ "
              "and/or you do not have an MPS-enabled device on this machine.")
    device = select_device(opt.device, batch_size=opt.batch_size)
else:
    device = torch.device("mps")
if LOCAL_RANK != -1:
    msg = 'is not compatible with YOLO Multi-GPU DDP training'
    assert not opt.image_weights, f'--image-weights {msg}'
    assert not opt.evolve, f'--evolve {msg}'
    assert opt.batch_size != -1, f'AutoBatch with --batch-size -1 {msg}, please pass a valid --batch-size'
    assert opt.batch_size % WORLD_SIZE == 0, f'--batch-size {opt.batch_size} must be multiple of WORLD_SIZE'
    assert torch.backends.mps.is_available(), "MPS not available. Check PyTorch build, macOS version, and hardware"
    # assert torch.cuda.device_count() > LOCAL_RANK, 'insufficient CUDA devices for DDP command'
    device = torch.device("mps")
    dist.init_process_group(backend="nccl" if dist.is_nccl_available() else "gloo")
```

batch-size = 8

I set the batch size to 8.

You can see that the GPU is indeed being used.
<img width="1507" alt="image" src="https://github.com/WongKinYiu/yolov9/assets/118149807/da600d2a-0883-4227-b919-db2787aa674b">

is it normal?
<img width="960" alt="image" src="https://github.com/WongKinYiu/yolov9/assets/118149807/3ffa35e4-156f-4238-8d9b-dee40369a312">

**Comment by wgqhandsome** [comment]
你用了 mps 加速吗

**Comment by wgqhandsome** [comment]
非常高兴能收到您的来消息。之前有机会使用PyTorch框架训练基于M2芯片的分类模型时，我注意到需要将GPU模式设置为MPS才能发挥作用，这一点与Windows或Linux系统下的设置有所不同。此外，我还尝试了在配备4090显卡的系统上使用Yolov9进行实验，具体是采用Yolov9c模型和一个包含1000张图片的数据集，将Epoch设置为100，在不到一个小时的时间内就完成了模型训练，这是我个人的一些实践经验分享。还有一些问题想要向您咨询，

1. 首先是遇到的参数量不匹配问题。我查看了一些相关资料（链接：https://github.com/WongKinYiu/yolov9/issues/122），了解到需要依照Yolov9-c.yaml和gelan-c.yaml将模型进行转换。我好奇，这样的转换操作是否会对模型的准确率产生影响？
2. 还有如何查看转化后的模型的参数量和计算量？
3. 如何利用产生的模型对jpg图像进行预测

非常期待您的回复

**Comment by kagura0108** [comment]
1. 关于将gpu设置为mps：
我发现除了在ddp mode里，还有其他地方需要更改。我一并更改了。
2. 对照你的信息，我的参数是
m2max 32GB
预训练权重：yolov9-c
epoch：10（epo2就爆掉了）
batch-size: 4
workers: 1
数据集规模：val 0 - 199，train 200 - 852
（如果遗漏请提醒我，我会补充）
3. 接下来的问题因为我还没训练了一个完整的数据，加上我学艺尚浅，我说一下我的推测。
可能因为您使用的模型配置文件与预训练模型不一致
4. 我通过查资料找到torchsummary库可能有用。
5. 可能需要您yolov9_model.pt自己的模型
进行
```
with torch.no_grad():
    outputs = model(image)
```
希望对您有帮助。
目前我还在更改程序，尝试运行成功。谢谢你。

**Comment by kagura0108** [comment]
我发现
`scaler = torch.cuda.amp.GradScaler(enabled=amp)`
这一句好像不太支持mps

**Comment by kagura0108** [comment]
我现在认为：
第一轮可能是预训练，
后面训练时间长达几个小时是一件很正常的事情。
