### ISSUE TITLE
Add comparison to YOLO enterprise SOTA like YOLO-NAS

### ISSUE THREAD

**Issue by AnshKetchum** [WongKinYiu/yolov9#17]
Can we add benchmarks comparing YOLOv9 to other variants, like [DeciAI's SOTA Yolo NAS](https://docs.ultralytics.com/models/yolo-nas/) ? 

It would also help put things into perspective with some of the more recent commercial variants for a more apt comparison.

**Comment by WongKinYiu** [comment]
From the [report](https://docs.ultralytics.com/zh/models/yolo-nas/).

| Model | Test Size | AP | Param. | 
| :-- | :-: | :-: |:-: |
| [**YOLOv9-S**]() | 640 | **46.8%** | **7.2M** |
| [**YOLOv9-M**]() | 640 | **51.4%** | **20.1M** |
| [**YOLOv9-C**]() | 640 | **53.0%** | **25.5M** |
| [**YOLOv9-E**]() | 640 | **55.6%** | **58.1M** |
|  |  |  |  |
| [**YOLO NAS-S**]() | 640 | **47.5%** | **19.0M** |
| [**YOLO NAS-M**]() | 640 | **51.6%** | **51.1M** |
| [**YOLO NAS-L**]() | 640 | **52.2%** | **66.9M** |
|  |  |  |  |
