### ISSUE TITLE
training speed is 3 times slower than yolov8

### ISSUE THREAD

**Issue by lazyfan** [WongKinYiu/yolov9#173]
my train dataset has 100k images for detection task

the following is a comparison of setting details and time
using 2*V100 on  Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz 
| model | batch | workers | training time (min/epoch) |
| :--: | :--: | :--: | :--: |
| yolov8x6 | 64 | 6 | 25| 
| yolov9-e | 36 | 6 | **75**| 

has anyone meet the same problem?

**Comment by WongKinYiu** [comment]
Yes, it is normal.

memory usage: forward+backword -> forward+2*backword (~ 1.5~2 times)
training time: update -> 2*update (~ 2 times)

If you adjust batch size depend on memory usage, the training time will around 3 times.

You could try gelan-e to check if its training time is faster than yolov8x6.

**Comment by lazyfan** [comment]
thank you very much for your answer!
