### ISSUE TITLE
为什么无法下载预训练模型呢？

### ISSUE THREAD

**Issue by Dreamcatcher-wind** [WongKinYiu/yolov9#184]
![image](https://github.com/WongKinYiu/yolov9/assets/82298413/4a42b83c-c199-463b-bf85-d062644b70b7)
点击红框里的任意一个模型，会又一次跳转到当前这个页面，而没有出现下载。请问是什么原因呢？

**Comment by WongKinYiu** [comment]
Currently only YOLOv9-C and YOLOV9-E are released.
