### ISSUE TITLE
validation loss in the training results is always 0

### ISSUE THREAD

**Issue by myabest** [WongKinYiu/yolov9#187]
I want to understand why the validation loss in the training results is always 0? Is there something wrong with my parameter settings?
![results](https://github.com/WongKinYiu/yolov9/assets/106659346/6e2e5d7a-5670-414a-ba51-3b3649775ee9)

**Comment by KyriakosChris** [comment]
I tried to retrain the yolov9-c with the visdrone-2019 dataset and i had the same issue

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/132#issuecomment-1972355045
