### ISSUE TITLE
ValueError: too many values to unpack (expected 13)

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [WongKinYiu/yolov9#193]
Thanks for working on this awesome project. 

when i run the following cmd: 
`python val.py --data data/coco.yaml --img 640 --batch 32 --conf 0.001 --iou 0.7 --device cpu --weights ./yolov9-c-converted.pt --save-json --name yolov9_c_c_640_val`
I get this error:
`    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 13)`

Python 3.11 ,  torch==2.2.0, and cuda 11.8 
os:ubuntu 20.04

**Comment by WongKinYiu** [comment]
Maybe fixed.

**Comment by SuroshAhmadZobair** [comment]
I just came here to post the fix. 
Thanks for the quick fix @WongKinYiu
