### ISSUE TITLE
window.cpp:1338: error: (-2:Unspecified error) The function is not implemented.

### ISSUE THREAD

**Issue by bikekowal** [WongKinYiu/yolov9#197]
Hi,

I experienced the following issue when tried to run YOLO9 with webcam
`window.cpp:1338:` error: (-2:Unspecified error) The function is not `implemented.`

Removing imshow and waitKey does not help here.

`                #cv2.imshow(str(p), im0)
                #cv2.waitKey(1)  # 1 `millisecond`

Any ideas?

**Comment by kishore-FDI** [comment]
got the solutions?

**Comment by bikekowal** [comment]
Yes, uninstall and install again opencv-python
