### ISSUE TITLE
has some exceptions

### ISSUE THREAD

**Issue by yoovor** [WongKinYiu/yolov9#204]
![image](https://github.com/WongKinYiu/yolov9/assets/85429342/0adf8b79-63ee-40e9-a28f-8edac2f54cf0)
why my detection has this exception?
my code below :
detect.py --weights=yolov9-c.pt --source=rtsp://192.168.0.112/D15.264 --device cpu --nosave

**Comment by Youho99** [comment]
Check #11

**Comment by WongKinYiu** [comment]
Please use `detect_dual.py`.
