### ISSUE TITLE
AttributeError: 'list' object has no attribute 'view'

### ISSUE THREAD

**Issue by qiu13579** [WongKinYiu/yolov9#22]
In loss_tal.py: pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
            (self.reg_max * 4, self.nc), 1)
The error is as follows：
AttributeError: 'list' object has no attribute 'view'

**Comment by WongKinYiu** [comment]
YOLOv9 models should be trained with `train_dual.py`

**Comment by qiu13579** [comment]
What is the difference between train.py and train_dual.py In terms of using training methods ?

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/1#issuecomment-1958742287

**Comment by qiu13579** [comment]
In general.py: device = prediction.device
The error is as follows：
AttributeError: 'list' object has no attribute 'device'

**Comment by WongKinYiu** [comment]
For inference, please check https://github.com/WongKinYiu/yolov9/issues/11#issuecomment-1960627261.

**Comment by qiu13579** [comment]
What is the difference between yolov9-c.pt and gelan-c.pt?  
In the train_dual.py, which weight file is commonly used to load pre training weights?

**Comment by WongKinYiu** [comment]
The details of GELAN and YOLOv9 are shown in the paper. Simply to say, YOLOv9 models contain additional aux branch for training. Our experiments are conduct with train-from-scratch strategy, so there are no pre-trained weights. If you want to fine-tune yolov9 on your dataset with `train_dual.py`, please use `yolov9-c.pt`.

**Comment by qiu13579** [comment]
In the train_dual.py, if '--weights' = 'yolov9-c.pt' , is '--cfg' = 'yolov9-c.yaml' ?

**Comment by korkmazemin1** [comment]
actually the solution is on the github readme page 
you should give the gelan-e.yaml  if u use train.py (for gelan)
and if u use train_dual.py (thats mean without gelan) you should give normal yaml

**Comment by korkmazemin1** [comment]
> The details of GELAN and YOLOv9 are shown in the paper. Simply to say, YOLOv9 models contain additional aux branch for training. Our experiments are conduct with train-from-scratch strategy, so there are no pre-trained weights. If you want to fine-tune yolov9 on your dataset with `train_dual.py`, please use `yolov9-c.pt`.

this is not a clear solution.
you should give the gelan-e.yaml  if u use train.py (for gelan)
and if u use train_dual.py (thats mean without gelan) you should give normal yaml 
you can check on the github readme page.
