### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by er778899789** [WongKinYiu/yolov9#233]
I meet the problem like title.
The yolov9/segment/predict.py inference result like below.
 
![image](https://github.com/WongKinYiu/yolov9/assets/32409355/e977b112-545e-45b0-9a9a-01b835c5520d)

And yolov7/segment/predict.py inference result like below.

![image](https://github.com/WongKinYiu/yolov9/assets/32409355/f27cd468-4339-4fc7-8e62-b750654a008a)

Yolov9 inference tensor's shape is not the same with Yolov7 inference tensor.

I find Yolov7 model inference code like below. I can run the code successfully with Yolov7 segment/predict.py !!

![image](https://github.com/WongKinYiu/yolov9/assets/32409355/a87a5ef5-e367-4b7a-9a6f-af9866237fc9)

I rewrite the same code in Yolov9 inference code, but the tensor shape is not the same, so I will get another error like below.

![image](https://github.com/WongKinYiu/yolov9/assets/32409355/9e3751f9-be96-4ed5-80e4-5a26fe538beb)

Has anyone run into the same problem before?
It will be appreciated if you could give me some suggestions！

**Comment by WongKinYiu** [comment]
The decoders (Segment) are different.
YOLOv7 is anchor-based, but YOLOv9 is anchor-free.

**Comment by er778899789** [comment]
@WongKinYiu Got it.
How can I solve the error?
I think the Yolov9 segment inference output tensor’s shape need to same with Yolov7?
Otherwise, it will always show the error like above.

**Comment by HanZhou1121** [comment]
I just added one line in the yolov9/segment/predict.py, and it worked.
# Inference
        with dt[1]:
            visualize = increment_path(save_dir / Path(path).stem, mkdir=True) if visualize else False
            pred, proto = model(im, augment=augment, visualize=visualize)[:2]
            proto = proto[-1]

**Comment by TheoLiu31** [comment]
I m facing the same error.
With this change, it works!

pred, proto = model(im, augment=augment, visualize=visualize)[:2]
proto = proto[2]

**Comment by blackCmd** [comment]
@TheoLiu31 
It works!

@WongKinYiu Plz edit code after read above~!

**Comment by igfujvjngu** [comment]
> 我面临同样的错误。有了这个变化，它就起作用了！
> 
> pred， proto = model（im， augment=augment， visualize=visualize）[：2] proto = proto[2]

Thanks very much

**Comment by Thompson21666** [comment]
> pred, proto = model(im, augment=augment, visualize=visualize)[:2]
> proto = proto[2]
你好，我想问一下这个应该添加到哪里？
