### ISSUE TITLE
What is the expected CUDA memory allocation for this model?

### ISSUE THREAD

**Issue by sam-looper-noteworthy** [WongKinYiu/yolov9#236]
Hello, 

I'm trying to get a sense of the expected necessary CUDA memory allocation for the YOLOv9 model, mostly to validate whether there are any errors or bottlenecks in my custom fork of this repository. 

I'm running the GELAN-E architecture (using train.py), using 1280x1280 image input size & nc=15. With a batch size of 4 I have 22GB allocated CUDA memory, and my GPU instance fails with a batch size > 4

What would you expect the memory footprint of a model like this to be, and is it roughly in line with what I'm seeing?

**Comment by guillermo-gabrielli-fer** [comment]
414x414 at bs=16 YOLOv9-C model takes ~11GB, 1280x1280 at bs=4 is ~9/4 the amount of pixels ~ 24GB so it roughly matches with a training I did recently. If anything it's more VRAM efficient than expected if you can run it at bs=4 with the E model.

**Comment by sam-looper-noteworthy** [comment]
Hey thanks for the validation! Glad to know it's not out of the ordinary
