### ISSUE TITLE
val_loss

### ISSUE THREAD

**Issue by roman-forever** [WongKinYiu/yolov9#257]
I am training YOLOV9 with box loss, cls loss, and dfl loss values of 0 for the three val, and it is not clear what is causing the results to be 0.when I open the calculation of val loss in train_dual.py, but an error was reported because the image size did not match. So what should I do?

**Comment by uitamaki** [comment]
@roman-forever I also encountered situations where box loss, cls loss, and dfl loss were all 0 during **validation**, but this does not affect the calculation of mAP or the convergence of the model. My trained model can be used normally.

**Comment by Youho99** [comment]
Please check #132
Use Gelan if you want val losses for the moment.

**Comment by roman-forever** [comment]
Since I had problems running train.py directly before, which showed 'RuntimeError: stack expects each tensor to be equal size, but got [1, 256, 32, 32] at entry 0 and [1, 192, 32, 32]'.
So I chose to train train_dual, if I now use 'python train_dual.py'to train the file and then use val.py for validation, is this a feasible operation?
If not, how do I fix the bug that 'python train.py' encounters.

**Comment by Youho99** [comment]
Read #1

If you train Yolov9 models, you need to use 'train_dual.py'
If you train Gelan models, you need to use 'train.py'

Val losses are only available for gelan models yet.
For Yolov9, try using val_dual.py for val losses (i never tried personnaly)

**Comment by roman-forever** [comment]
but when I used 'train.py'
it showed 'RuntimeError: stack expects each tensor to be equal size, but got [1, 256, 32, 32] at entry 0 and [1, 192, 32, 32]'.
how can i solve it

**Comment by Youho99** [comment]
Because you use yolov9 weights with train.py

Train.py ONLY for gelan weights
Train_dual.py ONLYfor yolov9 weights

**Comment by roman-forever** [comment]
I understand. Thank you very much
