### ISSUE TITLE
YoloV9 OBB

### ISSUE THREAD

**Issue by SwEngine** [WongKinYiu/yolov9#259]
Do you have any plan to develop YoloV9 OBB (Oriented-Bounding-Box)? It would be super beneficial!

**Comment by blackHorz** [comment]
Really really super beneficial feature for the person from Industrail background.

**Comment by WongKinYiu** [comment]
Currently only [yolov9u](https://github.com/WongKinYiu/yolov9/tree/yolov9u/ultralytics/cfg/models/v9) support it.

**Comment by SwEngine** [comment]
What is "yolov9u"? @WongKinYiu

**Comment by WongKinYiu** [comment]
"yolov9" implementation which based on "u"ltralytics.

**Comment by SwEngine** [comment]
Do you have any plan to release yolov9-tiny-obb? It would be super beneficial.

**Comment by shekarneo** [comment]
@WongKinYiu can we use this obb for commercial purpose
