### ISSUE TITLE
 where is yoloV9-s.pt and another weight？

### ISSUE THREAD

**Issue by machi9966** [WongKinYiu/yolov9#26]
Hello blogger, I'm in your project I just found yoloV9-c.pt ,and didn't find your other training weights like YoloV9-S etc.

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/3#issuecomment-1958745515

**Comment by machi9966** [comment]
thanks

**Comment by codewithleo1103** [comment]
waiting authors release....

**Comment by MAK1647** [comment]
Hello Guys, are these released all? Currently i have checked in "https://github.com/WongKinYiu/yolov9/releases/", it is still not released?

**Comment by WongKinYiu** [comment]
yolov9-s is released.
