### ISSUE TITLE
What is the difference between train_dual.py and train.py?

### ISSUE THREAD

**Issue by 1426618759** [WongKinYiu/yolov9#277]
Hello author,The same yolov9-c-converted.pt and yolov9-c yaml in train.py and train_dual.py running the same dataset in train_dual.py the MAP goes down should I use train_dual or train

**Comment by Youho99** [comment]
Check #1

**Comment by zyaiyw** [comment]
train.py for yolov9 models (with aux branch or without aux branch?)please help
