### ISSUE TITLE
AttributeError: Can't get attribute 'C3' on <module 'models.common' from 'D:\\Pycharm\\Projects\\yolo\\yolov9\\models\\common.py'>

### ISSUE THREAD

**Issue by Amireux-Serein** [WongKinYiu/yolov9#28]
This error occurs when I execute the following code: python classify/train.py --model yolov5s-cls.pt --data D:/Pycharm/Projects/zsh/data/2Dimage_AlliOne_split --epochs 5 --img 224

Here's the full info.

(yolo) PS D:\Pycharm\Projects\yolo\yolov9> python classify/train.py --model yolov5s-cls.pt --data D:/Pycharm/Projects/zsh/data/2Dimage_AlliOne_split --epochs 5 --img 224
classify\train: model=yolov5s-cls.pt, data=D:/Pycharm/Projects/zsh/data/2Dimage_AlliOne_split, epochs=5, batch_size=64, imgsz=224, nosave=False, cache=None, device=, workers=8, project=runs\train-cls, name=exp, exist_ok=False, pretrained=True, optimizer=Adam, lr0=0.001, decay=5e-05, label_smoothing=0.1, cutoff=None, dropout=None, verbose=False, seed=0, local_rank=-1
github: up to date with https://github.com/WongKinYiu/yolov9 
YOLOv5  v0.1-2-ge7d68de Python-3.11.5 torch-2.1.2+cu118 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)

TensorBoard: Start with 'tensorboard --logdir runs\train-cls', view at http://localhost:6006/
albumentations: RandomResizedCrop(p=1.0, height=224, width=224, scale=(0.08, 1.0), ratio=(0.75, 1.3333333333333333), interpolation=1), HorizontalFlip(p=0.5), ColorJitter(p=0.5, brightness=[0.6, 1.4], contrast=[0.6, 1.4], saturation=[0.6, 1.4], hue=[0, 0]), Normalize(p=1.0, mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0), ToTensorV2(always_apply=True, p=1.0, transpose_mask=False)
Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s-cls.pt to yolov5s-cls.pt...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.5M/10.5M [00:01<00:00, 6.13MB/s]

Traceback (most recent call last):
  File "D:\Pycharm\Projects\yolo\yolov9\classify\train.py", line 335, in <module>
    main(opt)
  File "D:\Pycharm\Projects\yolo\yolov9\classify\train.py", line 321, in main
    train(opt, device)
  File "D:\Pycharm\Projects\yolo\yolov9\classify\train.py", line 113, in train
    model = attempt_load(opt.model, device='cpu', fuse=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\Projects\yolo\yolov9\models\experimental.py", line 75, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\yolo\Lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\yolo\Lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\yolo\Lib\site-packages\torch\serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'C3' on <module 'models.common' from 'D:\\Pycharm\\Projects\\yolo\\yolov9\\models\\common.py'>

**Comment by WongKinYiu** [comment]
If you want to train yolov5 models, you need add C3 and related modules into `common.py` and `yolo.py`.

**Comment by Amireux-Serein** [comment]
> If you want to train yolov5 models, you need add C3 and related modules into `common.py` and `yolo.py`.

Thank you! It works.

**Comment by PhamTrinhDuc** [comment]
@Amireux-Serein How did you do it? Can you tell me in detail how you do it?

**Comment by dulda280** [comment]
> If you want to train yolov5 models, you need add C3 and related modules into `common.py` and `yolo.py`.

Hello, I'm running into the same problem, can you elaborate on how to do this?
