### ISSUE TITLE
How to remove the auxiliary reversible branch during the inference phase?

### ISSUE THREAD

**Issue by yujunzhen** [WongKinYiu/yolov9#293]

**Comment by yujunzhen** [comment]
When I get the training weights on a custom dataset, how do I remove the auxiliary branche during the inference phase? Is it necessary to transform the training weights into converted.pt?

**Comment by spacewalk01** [comment]
Yes, you can remove it by running reparameterization

**Comment by spacewalk01** [comment]
https://github.com/spacewalk01/TensorRT-YOLOv9

**Comment by yujunzhen** [comment]
> 下面是一个示例：https://github.com/spacewalk01/TensorRT-YOLOv9

OK, thank you!
