### ISSUE TITLE
Hope can also provide yolov9-s and m model,thanks

### ISSUE THREAD

**Issue by visonpon** [WongKinYiu/yolov9#3]

**Comment by WongKinYiu** [comment]
Currently we plan to release yolov9-s and m models after the paper is accepted and published. If our plan changes, we will directly release the models on the repo.

**Comment by xinsuinizhuan** [comment]
need to test the yolov9-s model, when to release them?

**Comment by huihui308** [comment]
Can you give us a time when s model release?

**Comment by xinsuinizhuan** [comment]
need yolov9-s和yolov9-n model? when release them?

**Comment by xinsuinizhuan** [comment]
release yolov9s and yolov9n model!!!

**Comment by stackByStack** [comment]
Sorry, but when could we know whether your models could released?

**Comment by MAK1647** [comment]
Hello Guys, are these released all? Currently i have checked in "https://github.com/WongKinYiu/yolov9/releases/", it is still not released?

**Comment by xinsuinizhuan** [comment]
still not release t and s model!! when to release them?

**Comment by zylo117** [comment]
这是什么操作？发布了成绩不公开模型权值，连模型配置、结构都不公开。非要说接收了论文才公开权值。是害怕被偷师改完抢发yolo10吗？要不要看看开源社区对yolov9的支持是怎么样的？是0，我没有看到任何第三方框架宣布对yolov9的支持。正因为作者迟迟不公开细节，人家都不知道怎么复现。
作者既不急着认自己是正统，又害怕别人抢了作者的正统，就挺怪的。

**Comment by wenhui-ml** [comment]
close yolov9, yolov7-plus will be nice.
Your Team is going ahead just as Close-AI.

**Comment by SMRaza1009** [comment]
Is there any way to contribute in  YOLOv9? For model releasing or any other thing required

**Comment by xinsuinizhuan** [comment]
> Is there any way to contribute in YOLOv9? For model releasing or any other thing required

go to use the yolov10, v10 is better.

**Comment by WongKinYiu** [comment]
yolov9-s and yolov9-m are released, you could try them.

**Comment by zylo117** [comment]
> yolov9-s and yolov9-m are released, you could try them.

让你藏着掖着，现在好了，没多少人用上yolo9，直接上yolo10了

**Comment by MAK1647** [comment]
Thank you very much!
Let us try

**Comment by aaron-hgx** [comment]
> yolov9-s and yolov9-m are released, you could try them.

Thanks!
Why is there no auxillary branch in YOLOv9-s model? I couldnt find in the config file? Would be really grateful if you could explain.

**Comment by WongKinYiu** [comment]
[yolov9-m](https://github.com/WongKinYiu/yolov9/blob/main/models/detect/yolov9-m.yaml) and [yolov9-s](https://github.com/WongKinYiu/yolov9/blob/main/models/detect/yolov9-s.yaml) have auxiliary branch. 
Provided weights files are reparameterized, which auxiliary branch have removed.

**Comment by aaron-hgx** [comment]
I understand that the weight files are re-parametrized. However, I do not get why I do not see reversible aux branch in the config file like in the YOLOv9-C config file(which has the comment showing multi-level aux branch part). Can you please explain if i am missing something basic? I would be grateful if you could pinpoint the branches.
# YOLOv9

# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
#activation: nn.LeakyReLU(0.1)
#activation: nn.ReLU()

# anchors
anchors: 3

# gelan backbone
backbone:
  [
   # conv down
   [-1, 1, Conv, [32, 3, 2]],  # 0-P1/2

   # conv down
   [-1, 1, Conv, [64, 3, 2]],  # 1-P2/4

   # elan-1 block
   [-1, 1, ELAN1, [64, 64, 32]],  # 2

   # avg-conv down
   [-1, 1, AConv, [128]],  # 3-P3/8

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [128, 128, 64, 3]],  # 4

   # avg-conv down
   [-1, 1, AConv, [192]],  # 5-P4/16

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [192, 192, 96, 3]],  # 6

   # avg-conv down
   [-1, 1, AConv, [256]],  # 7-P5/32

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [256, 256, 128, 3]],  # 8
  ]

# elan head
head:
  [
   # elan-spp block
   [-1, 1, SPPELAN, [256, 128]],  # 9

   # up-concat merge
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [192, 192, 96, 3]],  # 12

   # up-concat merge
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [128, 128, 64, 3]],  # 15

   # avg-conv-down merge
   [-1, 1, AConv, [96]],
   [[-1, 12], 1, Concat, [1]],  # cat head P4

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [192, 192, 96, 3]],  # 18 (P4/16-medium)

   # avg-conv-down merge
   [-1, 1, AConv, [128]],
   [[-1, 9], 1, Concat, [1]],  # cat head P5

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [256, 256, 128, 3]],  # 21 (P5/32-large)
   
   # elan-spp block
   [8, 1, SPPELAN, [256, 128]],  # 22

   # up-concat merge
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [192, 192, 96, 3]],  # 25

   # up-concat merge
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [128, 128, 64, 3]],  # 28

   # detect
   [[28, 25, 22, 15, 18, 21], 1, DualDDetect, [nc]],  # Detect(P3, P4, P5)
  ]

**Comment by WongKinYiu** [comment]
yolov9-m use [multi-level reversible aux branch](https://github.com/WongKinYiu/yolov9/blob/main/models/detect/yolov9-m.yaml#L80-L113).
yolov9-s use [multi-level aux branch](https://github.com/WongKinYiu/yolov9/blob/main/models/detect/yolov9-s.yaml#L78C3-L93).

**Comment by felixkarevo** [comment]
Do you plan to release a smaller version of YOLOv9 for segmentation tasks? Smaller than yolov9c-seg.

**Comment by Zhengcv** [comment]
Can you provide the parameter configuration for YOLOv9s on the COCO dataset, especially the key settings for data augmentation such as mixup, scale, and copy-paste? You mentioned the parameters in the paper—are these default parameters applicable to all models?
