### ISSUE TITLE
AttributeError: 'list' object has no attribute 'view'

### ISSUE THREAD

**Issue by KaiNKaiHo** [WongKinYiu/yolov9#302]
Hi!!
I'm just trying to train yolov9c for single class and when I run this command:
`!python train.py \
--batch 8 --epochs 200 --img 640 --device 0 \
--data data.yaml \
--weights yolov9c.pt \
--cfg cfg.yaml \
--hyp hyp.yaml \
--single-cls `

This error show up:

>...
> Starting training for 200 epochs...
> 
>       Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
>   0% 0/175 [00:01<?, ?it/s]
> Traceback (most recent call last):
>   File "/content/drive/MyDrive/BienSoxe/Yolov9/yolov9/train.py", line 634, in <module>
>     main(opt)
>   File "/content/drive/MyDrive/BienSoxe/Yolov9/yolov9/train.py", line 528, in main
>     train(opt.hyp, opt, device, callbacks)
>   File "/content/drive/MyDrive/BienSoxe/Yolov9/yolov9/train.py", line 304, in train
>     loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
>   File "/content/drive/MyDrive/BienSoxe/Yolov9/yolov9/utils/loss_tal.py", line 168, in __call__
>     pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
>   File "/content/drive/MyDrive/BienSoxe/Yolov9/yolov9/utils/loss_tal.py", line 168, in <listcomp>
>     pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
> AttributeError: 'list' object has no attribute 'view'

Please help me fix this.

**Comment by Youho99** [comment]
train.py is only for gelan models
Use train_dual.py for yolov9 model (here yolov9-c)
