### ISSUE TITLE
Issue when run detect.py

### ISSUE THREAD

**Issue by QuangNguyenPT** [WongKinYiu/yolov9#306]
I had try run inference with original .pt ( i think so, I'm not sure ) I download it from v0.1 and after run i gives me 
yolov9-c-converted.pt' --name yolov9-test
detect: weights=["'./yolov9-c-converted.pt'"], source='./1.png', data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=yolov9-test, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLO  v0.1-76-g519346b Python-3.11.8 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB)

Traceback (most recent call last):
  File "C:\Users\phuoc\OneDrive\Desktop\All-in-One\Coding\yolov9\detect.py", line 231, in <module>
    main(opt)
  File "C:\Users\phuoc\OneDrive\Desktop\All-in-One\Coding\yolov9\detect.py", line 226, in main
    run(**vars(opt))
  File "C:\Users\phuoc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phuoc\OneDrive\Desktop\All-in-One\Coding\yolov9\detect.py", line 68, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phuoc\OneDrive\Desktop\All-in-One\Coding\yolov9\models\common.py", line 675, in __init__
    pt, jit, onnx, onnx_end2end, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
                                                                                                               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phuoc\OneDrive\Desktop\All-in-One\Coding\yolov9\models\common.py", line 946, in _model_type
    check_suffix(p, sf)  # checks
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phuoc\OneDrive\Desktop\All-in-One\Coding\yolov9\utils\general.py", line 447, in check_suffix
    assert s in suffix, f"{msg}{f} acceptable suffix is {suffix}"
           ^^^^^^^^^^^
AssertionError: './yolov9-c-converted.pt' acceptable suffix is ['.pt', '.torchscript', '.onnx', '_end2end.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '_paddle_model']
I had try to find answer on other platform/ forum bit I basically can't find it. What should and what can I do?

**Comment by WongKinYiu** [comment]
from your log
`weights=["'./yolov9-c-converted.pt'"]`

there are both `''` and `""`, so just change `'yolov9-c-converted.pt'` to `yolov9-c-converted.pt` in your command

**Comment by QuangNguyenPT** [comment]
I'm not sure if it fix or not because I can't run it yet. My python has
some problems with modules :v so I will test it later but I think it may be
good now.

Vào CN, 31 thg 3, 2024 vào lúc 06:01 Kin-Yiu, Wong <
***@***.***> đã viết:

**Comment by QuangNguyenPT** [comment]
Thnks @WongKinYiu I had test it and it worked tysm.
