### ISSUE TITLE
GELAN Implementation

### ISSUE THREAD

**Issue by StunningVisionAI** [WongKinYiu/yolov9#309]
Dear author,
I have a question about the implementation of GELAN.
I see that in your paper, the GELAN has 3 "any block"
![image](https://github.com/WongKinYiu/yolov9/assets/83331756/c25256da-8bf1-42c2-a9c2-0fd1addf6bec)

When i see the source code about GELAN in models/common.py, There were just two "any block": **self.cv2** and **self.cv3**. is it like that ?
```
class RepNCSPELAN4(nn.Module):
    # csp-elan
    def __init__(self, c1, c2, c3, c4, c5=1):  # ch_in, ch_out, number, shortcut, groups, expansion
        super().__init__()
        self.c = c3//2
        self.cv1 = Conv(c1, c3, 1, 1)
        self.cv2 = nn.Sequential(RepNCSP(c3//2, c4, c5), Conv(c4, c4, 3, 1))
        self.cv3 = nn.Sequential(RepNCSP(c4, c4, c5), Conv(c4, c4, 3, 1))
        self.cv4 = Conv(c3+(2*c4), c2, 1, 1)

    def forward(self, x):
        y = list(self.cv1(x).chunk(2, 1))
        y.extend((m(y[-1])) for m in [self.cv2, self.cv3])
        return self.cv4(torch.cat(y, 1))

    def forward_split(self, x):
        y = list(self.cv1(x).split((self.c, self.c), 1))
        y.extend(m(y[-1]) for m in [self.cv2, self.cv3])
        return self.cv4(torch.cat(y, 1))
```

Thank You

**Comment by WongKinYiu** [comment]
![image](https://github.com/WongKinYiu/yolov9/assets/12152972/038ee8b8-8c53-42ab-b516-f0c40aff4c67)

How many any blocks is D_ELAN, repeat how many times in CSP block is D_CSP.

**Comment by StunningVisionAI** [comment]
In pretrained weights yolov9-c.pt which combination is used ?

**Comment by WongKinYiu** [comment]
\{2,1\}

**Comment by StunningVisionAI** [comment]
Thank you
