### ISSUE TITLE
detect.py no detections

### ISSUE THREAD

**Issue by ZhouBay-TF** [WongKinYiu/yolov9#313]
When I used my own trained model, the prediction was 0.8, but when testing with detect.py, it did not show that no targets were detected. However, when I used the same data, I only reduced the training size, and the resulting model was able to detect normally with detect.py

**Comment by ZhouBay-TF** [comment]
Supplementary questions，The input of the undetectable model is 1280 * 1280, and the correct operation is 640 * 640

**Comment by Youho99** [comment]
What is the image size in your training ?

**Comment by ZhouBay-TF** [comment]
> What is the image size in your training ?
My training size is 1280, val.py verifies that 1280 is normal, detect.py cannot detect targets using 1280.

**Comment by ZhouBay-TF** [comment]
I found that there is network output, but when "xc=prediction [:, 4: mi]. amax (1)>conf_thres # candidates", the output is all false, regardless of how small the conf is set, but there are no issues with the code for other models, so I have temporarily closed this issue.

**Comment by zrg0712** [comment]
I had the same question,  how did you solve it?

**Comment by zrg0712** [comment]
I had the same question,  how did you solve it?

**Comment by SufyanDanish** [comment]
i have the same issue. did you solve it
