### ISSUE TITLE
train.py 'list' object has no attribute 'view;

### ISSUE THREAD

**Issue by prammmoe** [WongKinYiu/yolov9#315]
![image](https://github.com/WongKinYiu/yolov9/assets/95534357/b0e46c25-4b2d-4f64-b93d-d5461754ed38)

I want to train my custom models using the train.py script and it shows error as shown in the image, could someone help me resolve this issue? thanks in advance

**Comment by Youho99** [comment]
Read Issue #1
Train.py is only for gelan models
Train_dual.py IS only for yolov9 models

Use train_dual.py

**Comment by prammmoe** [comment]
i see, thank you so much!
