### ISSUE TITLE
Yolo Keypoint Detection

### ISSUE THREAD

**Issue by legenda971** [WongKinYiu/yolov9#317]
Is it possible to adapt a YOLO-based model for keypoint detection, distinct from the YOLO pose estimation models which exhibit several limitations? I'm interested in a method DFL that focuses solely on predicting keypoints.

**Comment by WongKinYiu** [comment]
Currently only [yolov9u](https://github.com/WongKinYiu/yolov9/tree/yolov9u/ultralytics/cfg/models/v9) support keypoint detection.
