### ISSUE TITLE
Why is auxiliary invertible branch still used in the model inference in the code, which is inconsistent with what is mentioned in the paper. Can we consider not using auxiliary invertible branch in inference?

### ISSUE THREAD

**Issue by BeRikes** [WongKinYiu/yolov9#318]
Why is auxiliary invertible branch still used in the model inference in the code, which is inconsistent with what is mentioned in the paper. Can we consider not using auxiliary invertible branch in inference?
This reduces the calculation and time of inference.

**Comment by guillermo-gabrielli-fer** [comment]
The re-parameterization removes the auxiliary branch.

**Comment by BeRikes** [comment]
@guillermo-gabrielli-fer Thanks for your reply, but I debug the code in detect_dual.py and found that when the model inference, the forward propagation process still goes through the auxiliary reversible branch, which naturally increases the inference time

**Comment by guillermo-gabrielli-fer** [comment]
I think detect_dual.py is only useful to double check that the conversion is correct. You would normally use detect.py with the converted model.

**Comment by BeRikes** [comment]
@guillermo-gabrielli-fer Thanks for your reply! I found the problem that had been solved before, I found the answer. You're right!
#52
