### ISSUE TITLE
what does yolov7 AF mean?

### ISSUE THREAD

**Issue by lyy1988323** [WongKinYiu/yolov9#32]
in the [yolov9 official paper](https://arxiv.org/pdf/2402.13616.pdf), I see some new words about yolov7
![captrue](https://github.com/WongKinYiu/yolov9/assets/26386193/c586179b-b18d-4ce4-a805-513be26bea46)
any one who know what does it mean "yolov7 AF" or "yolov7-N AF" or "yolov7-S AF"
I don't see more explaination in [yolov9 official paper](https://arxiv.org/pdf/2402.13616.pdf) or [yolov7 official paper](https://arxiv.org/abs/2207.02696)

**Comment by WongKinYiu** [comment]
AF means anchor-free, it described in supplementary of [yolov7](https://openaccess.thecvf.com/content/CVPR2023/html/Wang_YOLOv7_Trainable_Bag-of-Freebies_Sets_New_State-of-the-Art_for_Real-Time_Object_Detectors_CVPR_2023_paper.html).
