### ISSUE TITLE
Where are the yolov9-s.yaml and yolov9-m.yaml files located?

### ISSUE THREAD

**Issue by flinzhao** [WongKinYiu/yolov9#35]
![image](https://github.com/WongKinYiu/yolov9/assets/103496889/893163a1-8d93-4518-944d-4c4490540dbf)
Great support for your work! Where can I find the yolov9-s.yaml and yolov9-m.yaml files?

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/3#issuecomment-1958745515
