### ISSUE TITLE
i want to learn more about the DualDDetector

### ISSUE THREAD

**Issue by leangovern** [WongKinYiu/yolov9#36]
Hello, I want to know more information about DualDDetector. Is there any relevant literature? Maybe I didn't read the original literature carefully and couldn't find relevant information. Thank you very much!!!!

**Comment by WongKinYiu** [comment]
DualDDetect is concatenation of two DDetect, and DDetect is a fully decoupled Detect module.

**Comment by MuhammadWaqar621** [comment]
Huge thanks to the folks behind these YOLO models. They're doing some awesome work!

Quick thing, I'm curious about the different training scripts – train.py, train_dual.py, and train_triple.py. Why the need for separate scripts based on the number of GPUs? In the past, we could just pick a GPU with an ID. What's the story behind these variations? Appreciate the insights!

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/1#issuecomment-1958742287
