### ISSUE TITLE
Segmentation Model for Yolo v9

### ISSUE THREAD

**Issue by WuZhuoran** [WongKinYiu/yolov9#39]
Any plan to make segmentation model? I saw you already used some Multi Task Yolo model code. Thank you for your work.

**Comment by B4RT1M** [comment]
Hi, I wanted to ask the same. 
The segment folder already exists and the train.py script looks similar to the yolov7 version to me. 
Will you provide the yolo-seg.pt weights? Or can I use the pretrained weights provided for yolov7? 
When I am trying to train from scratch with the provided yolov7-af-seg.yaml cfg file I am facing the following issue: 

Traceback (most recent call last):
  File "segment/train.py", line 646, in <module>
    main(opt)
  File "segment/train.py", line 542, in main
    train(opt.hyp, opt, device, callbacks)
  File "segment/train.py", line 220, in train
    hyp['obj'] *= (imgsz / 640) ** 2 * 3 / nl  # scale to image size and layers
KeyError: 'obj'

**Comment by WongKinYiu** [comment]
Code for multi-task will be release in the future.

**Comment by marziyemahmoudifar** [comment]
> Hi, I wanted to ask the same. The segment folder already exists and the train.py script looks similar to the yolov7 version to me. Will you provide the yolo-seg.pt weights? Or can I use the pretrained weights provided for yolov7? When I am trying to train from scratch with the provided yolov7-af-seg.yaml cfg file I am facing the following issue:
> 
> Traceback (most recent call last): File "segment/train.py", line 646, in main(opt) File "segment/train.py", line 542, in main train(opt.hyp, opt, device, callbacks) File "segment/train.py", line 220, in train hyp['obj'] *= (imgsz / 640) ** 2 * 3 / nl # scale to image size and layers KeyError: 'obj'
> 
> Edit: By changing line 11: "dfl: 0.7" to "obj: 0.7" it seems to work now. Still some pretrained weights will be appreciated.

Hi dear
I have similar error, can you guide me to solve it?
