### ISSUE TITLE
Question about training time and hardware

### ISSUE THREAD

**Issue by DrRyanHuang** [WongKinYiu/yolov9#4]
Hi, thx for your great work!

I noticed that the experiment requires training from scratch for 500 epochs. 
Could you please tell me your training time and corresponding GPU device?

**Comment by WongKinYiu** [comment]
Small models, 2080ti\*8, about 2 days.
Compact models, 3090\*8, about 2.5 days.

**Comment by DrRyanHuang** [comment]
Thx for your reply.
