### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 0 with size 1 while using detect.py in yolov9

### ISSUE THREAD

**Issue by SufyanDanish** [WongKinYiu/yolov9#432]
I have an issue with index inferencing with the Custom dataset. When it is used the following command, I get the following error "
detect: weights=['E:/Research_Paper/Detection/second_task_on_detection/yolov9/runs/train/exp18/weights/best.pt'], source=E:/Research_Paper/Detection/second_task_on_detection/yolov9/fire/test/images, data=data\coco128.yaml, imgsz=[1280, 1280], conf_thres=0.1, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLO  2024-5-9 Python-3.9.19 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

Fusing layers... 
yolov9_custom summary: 576 layers, 70282908 parameters, 0 gradients, 313.4 GFLOPs
Traceback (most recent call last):
  File "E:\second_task_on_detection\yolov9\detect.py", line 231, in <module>
    main(opt)
  File "E:\second_task_on_detection\yolov9\detect.py", line 226, in main
    run(**vars(opt))
  File "C:\Users\.conda\envs\yolov9\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\second_task_on_detection\yolov9\detect.py", line 102, in run
    pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
  File "E:\second_task_on_detection\yolov9\utils\general.py", line 903, in non_max_suppression
    prediction = prediction[0][1]  # select only inference output
IndexError: index 1 is out of bounds for dimension 0 with size 1"

Training command:

"!python train.py --workers 8 --batch 8  --img 640 --epochs 2 --data E:/second_task_on_detection/yolov9/data.yaml --weights E:/second_task_on_detection/yolov9/yolov9-e.pt --device 0 --cfg E:/second_task_on_detection/yolov9/models/detect/yolov9_custom.yaml --hyp E:/second_task_on_detection/yolov9/data/hyps/hyp.scratch-high.yaml"

inference with the Custom dataset

"!python detect.py --img 1280 --conf 0.1 --device 0 --weights E:/second_task_on_detection/yolov9/runs/train/exp18/weights/best.pt --source E:/second_task_on_detection/yolov9/fire/test/images"
"

Thanks in advance

**Comment by SufyanDanish** [comment]
i have fixed the above error 
prediction = prediction[0][1] to prediction = prediction[0]
in general.py file located in yolov9\utils folder.

**Comment by WongKinYiu** [comment]
Please use detect_dual.py.
