### ISSUE TITLE
export openvino error

### ISSUE THREAD

**Issue by the-cat-crying** [WongKinYiu/yolov9#441]
![image](https://github.com/WongKinYiu/yolov9/assets/52776417/1f4b9838-ef48-4602-b757-af934aa3a6d3)
![image](https://github.com/WongKinYiu/yolov9/assets/52776417/909d379b-b8d2-4fe0-af84-9f8790a594c7)

**Comment by StijnPruijssers** [comment]
OpenVINO Inference Engine Python API is deprecated and will be removed in 2024.0 release. For me downgrading to 2023.3 worked.

**Comment by the-cat-crying** [comment]
Thanks!
