### ISSUE TITLE
question about val.py

### ISSUE THREAD

**Issue by lbwzv** [WongKinYiu/yolov9#444]
hello!
When I use Val. py to verify the model without reparameterization, the following errors will occur. The model can be modified and inference can be done normally using Detect. py. The reparameterization process is executed according to the reparameterization file, and the nc of gelan-c. yaml is consistent with the model=Model (cfg, ch=3, nc=80, anchors=3). But using val.py will result in
Traceback (most recent call last):
  File "val.py", line 390, in <module>
    main(opt)
  File "val.py", line 363, in main
    run(**vars(opt))
  File "/home/zhkj/.pyenv/versions/3.8.10/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 214, in run
    path, shape = Path(paths[si]), shapes[si][0]
IndexError: list index out of range

But it's normal for me to use val_dual.py to validate the model before reparameterization

**Comment by WongKinYiu** [comment]
to verify the model without reparameterization, please use `val_dual.py`.
