### ISSUE TITLE
Upload models over to the Hugging Face Hub! 🤗

### ISSUE THREAD

**Issue by Vaibhavs10** [WongKinYiu/yolov9#45]
Hi there,

I'm VB I lead the advocacy efforts for open source at Hugging Face. Congratulations on such a brilliant model. I saw that the model checkpoints are released as part of the GitHub release. It'd be great if you could upload the model checkpoints over the Hugging Face Hub.

Uploading model checkpoints over on Hugging Face Hub comes with a couple of advantages:
1. It increases the visibility of the model checkpoints on the Hub.
2. It makes it easier for people to download the different weights.
3. It makes it surprisingly easy to version control weights as well.

Here's a quick guide explaining how to upload models over on the Hub: https://huggingface.co/docs/hub/en/models-uploading

In addition to this, you can add support for directly loading the model checkpoints via the `huggingface_hub` library as well: https://huggingface.co/docs/huggingface_hub/v0.16.3/en/guides/download (it's just 2 lines of code).

Do let me or @merveenoyan know if you need any assistance with this.

Cheers,
VB

**Comment by merveenoyan** [comment]
Hello folks 👋 

I have uploaded the weights and written a model card here: https://huggingface.co/merve/yolov9
If you have a Hugging Face organization I can transfer this repository to your organization namespace.

Also wanted to let you know that @kadirnar has put up a demo here: https://huggingface.co/spaces/kadirnar/Yolov9

**Comment by VellalaVineethKumar** [comment]
Here is a Python file to run the code on your webcam from a single Python file given you have downloaded the the required libraries, weights, and coco.yaml file.
https://file.io/vXaO7OAJcS85
