### ISSUE TITLE
P,R,mAP50 and mAP50-95 is all 0

### ISSUE THREAD

**Issue by Jocat-6** [WongKinYiu/yolov9#453]
What the authors did on the COCO dataset were 80 categories. When I try to do face detection with YOLOv9, I notice that there is a parameter nc in the models\detect\yolov9-c.yaml file is 80.
![image](https://github.com/WongKinYiu/yolov9/assets/71422217/a16f9fad-7fc9-468f-8a85-e84d5074a6cc)
After I modified the value of nc to 1, I found that the values of P, R, mAP50 and mAP50-95 were all 0 when training.
![image](https://github.com/WongKinYiu/yolov9/assets/71422217/37c674dd-13b1-45a3-82ae-c645374ac855)
The values of these parameters that were trained before modifying nc are normal. After the exception, I changed the value of nc back to 80 for training, and the exception persisted.

Env:
 - Python 3.9
 - GPU RTX3070

**Comment by Jocat-6** [comment]
I'm using train_dual.py file training.

**Comment by yjmuma** [comment]
utils的有个general，将general.py里903行的prediction[0][0]改回prediction[0]就显示正常了。要使用val.py的时候再改成prediction[0][0]

**Comment by Jocat-6** [comment]
Thank you for the approach
