### ISSUE TITLE
YOLOv9-e with 69M parameters

### ISSUE THREAD

**Issue by NamanMakkar** [WongKinYiu/yolov9#46]
Hello, I was just training the YOLOv9-e model on the VisDrone dataset and noticed that it was showing me 69 million parameters instead of 58 million parameters which was mentioned in the README.

**Comment by WongKinYiu** [comment]
Additional parameters are from auxiliary branch, they could be removed at the inference stage.

**Comment by rtakak** [comment]
@NamanMakkar is it possible for you to share the trained model with us?

**Comment by Huo-Yukang** [comment]
> Additional parameters are from auxiliary branch, they could be removed at the inference stage.

Can you briefly describe how to remove auxiliary branches during the inference phase?

**Comment by Huo-Yukang** [comment]
> Hello, I was just training the YOLOv9-e model on the VisDrone dataset and noticed that it was showing me 69 million parameters instead of 58 million parameters which was mentioned in the README.

Have you deleted the auxiliary branches during the inference stage?

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization

**Comment by Huo-Yukang** [comment]
> https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization

Thank you very much for your reply. However, the parameter amount of the weight file after I use this method is indeed the same as that in the README. However, when I load this modified pre-training weight file during training, the parameter amount of the model is still the same as the original one.
