### ISSUE TITLE
Have you done any newest work for human pose estimation (HPE)?

### ISSUE THREAD

**Issue by qingtianwu** [WongKinYiu/yolov9#5]
Thank you for conducting a lot of experiments and making new progress. Since YOLOv5, 7, and 8 all provide code for HPE. Does the latest v9 do this task?

**Comment by WongKinYiu** [comment]
We have not integrate this work with pose estimation. Currently this repo share same code base with "YOLOR-Based Multi-Task Learning", we will support tasks in the paper in the futrue.
