### ISSUE TITLE
how to remove auxiliary branch

### ISSUE THREAD

**Issue by bailaneveryday** [WongKinYiu/yolov9#52]
Hello, thank you for your excellent work, but I didn't find the code on how to remove the auxiliary branch, can you help me?

**Comment by Youho99** [comment]
Use train.py for gelan for gelan models (without aux branchs) and train_dual.py for yolov9 models (with aux branch).

**Comment by Youho99** [comment]
#1 (comment)

**Comment by bailaneveryday** [comment]
I know these three files, I have compared these three training files and there is a difference in calculating the LOSS, but loading and saving the model is the same. I mean, if I use train_dual.py for training and save the weights and model with auxiliary branches, how do I remove the auxiliary branches in detect?

**Comment by lsutardja** [comment]
Take a look at this from yolov7 https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb

Load yolov9 model (model with auxiliary branches) and a new gelan model. This is equivalent to the train and deploy respectively in the above code. Move the weights and biases from the lead detection head to the new gelan model in the correct position. Ffor yolov9-c you want to move index 38 to index 22 and for yolov9-e you want to move index 49 to index 42. 

When moving the weights and biases of everything you have to take into account that there is a Silence module added only in the yolov9 models. The Silence module is basically nn.Identity, it can be removed so rebase everything in the trained model by subtracting all indices by 1.

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization
