### ISSUE TITLE
Getting Assertion Error while using panoptic segmentation

### ISSUE THREAD

**Issue by plutus123** [WongKinYiu/yolov9#535]
`!python panoptic/train.py --workers 8 --device 0 --batch 32  --data WALL-INSTANCEE-2/data.yaml --img 640 --cfg models/panoptic/gelan-c-pan-custom.yaml --weights '' --name gelan-c-pan --hyp hyp.scratch-high.yaml --no-overlap --epochs 100 --close-mosaic 10`

train: New cache created: /workspace/yolov9-pan/WALL-INSTANCEE-2/train/stuff_stuff.cache
Traceback (most recent call last):
  File "/workspace/yolov9-pan/panoptic/train.py", line 662, in <module>
    main(opt)
  File "/workspace/yolov9-pan/panoptic/train.py", line 558, in main
    train(opt.hyp, opt, device, callbacks)
  File "/workspace/yolov9-pan/panoptic/train.py", line 169, in train
    train_loader, dataset = create_dataloader(
  File "/workspace/yolov9-pan/utils/panoptic/dataloaders.py", line 49, in create_dataloader
    dataset = LoadImagesAndLabelsAndMasks(
  File "/workspace/yolov9-pan/utils/panoptic/dataloaders.py", line 150, in __init__
    assert (0 < nf) or (not augment), f'{prefix}No labels found in {cache_path}, can not start training. {HELP_URL}'
AssertionError: train: No labels found in /workspace/yolov9-pan/WALL-INSTANCEE-2/train/stuff_stuff.cache, can not start training. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

**Comment by foxkw** [comment]
> `!python panoptic/train.py --workers 8 --device 0 --batch 32 --data WALL-INSTANCEE-2/data.yaml --img 640 --cfg models/panoptic/gelan-c-pan-custom.yaml --weights '' --name gelan-c-pan --hyp hyp.scratch-high.yaml --no-overlap --epochs 100 --close-mosaic 10`
> 
> train: New cache created: /workspace/yolov9-pan/WALL-INSTANCEE-2/train/stuff_stuff.cache Traceback (most recent call last): File "/workspace/yolov9-pan/panoptic/train.py", line 662, in main(opt) File "/workspace/yolov9-pan/panoptic/train.py", line 558, in main train(opt.hyp, opt, device, callbacks) File "/workspace/yolov9-pan/panoptic/train.py", line 169, in train train_loader, dataset = create_dataloader( File "/workspace/yolov9-pan/utils/panoptic/dataloaders.py", line 49, in create_dataloader dataset = LoadImagesAndLabelsAndMasks( File "/workspace/yolov9-pan/utils/panoptic/dataloaders.py", line 150, in **init** assert (0 < nf) or (not augment), f'{prefix}No labels found in {cache_path}, can not start training. {HELP_URL}' AssertionError: train: No labels found in /workspace/yolov9-pan/WALL-INSTANCEE-2/train/stuff_stuff.cache, can not start training. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

Have you resloved it ? I met the same question
