### ISSUE TITLE
cls = names[cls] if names else cls KeyError: 79

### ISSUE THREAD

**Issue by binisalegend** [WongKinYiu/yolov9#54]
After the training procedure completed, I encountered an error as shown below: 
~~~python
Fusing layers... 

Exception in thread Thread-9:

Traceback (most recent call last):

  File "/home/.../miniconda3/envs/YOLOv9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/.../miniconda3/envs/YOLOv9/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/.../yolov9/utils/plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 79
<class 'torch.Tensor'>
~~~

It seems that the weight file `best.pt` has been successfully saved, but the evaluation diagram of the results is not correct

**Comment by WongKinYiu** [comment]
Please check both of your dataset.yaml and model.yaml if the class number is correct.

**Comment by binisalegend** [comment]
> Please check both of your dataset.yaml and model.yaml if the class number is correct.

Thanks! The problem has been solved.

**Comment by weldingCode** [comment]
_python val.py --data /datasets/coco8.yaml --img 640 --batch 32 --device 0 --weights '/runs/train/gelan9-c2/weights/best.pt'_

The same issue encountered when running the above command!

**Comment by lc1234567484848** [comment]
> _python val.py --data /datasets/coco8.yaml --img 640 --batch 32 --device 0 --weights '/runs/train/gelan9-c2/weights/best.pt'_
> 
> 当我尝试评估 Gelan 模型时，我遇到了相同的错误消息。

请问您解决了，我也遇到了这个问题
