### ISSUE TITLE
AttributeError: 'list' object has no attribute 'device

### ISSUE THREAD

**Issue by geniusalert** [WongKinYiu/yolov9#59]

**Comment by Nikhiljha10** [comment]
In this case, it seems like you're trying to access the device attribute on a list object, but lists in Python don't have a device attribute.

Here's an example of how this error might occur:

python code

```
my_list = [1, 2, 3, 4]
device_name = my_list.device # This line will raise AttributeError
```
To fix this issue, you need to make sure that you're accessing the device attribute on the correct object. If you're working with a list and you need to associate a device with it, you might need to rethink your approach or check if you're using a library that expects a different type of object.

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/11
