### ISSUE TITLE
Yolov9 Nano Version

### ISSUE THREAD

**Issue by SwEngine** [WongKinYiu/yolov9#60]
Hi, thanks for this great work! For real time low level systems, we need yolov9 nano models. Are you planning to release nano version?

**Comment by WongKinYiu** [comment]
Maybe release with s and m models at same time. 
In our plan, s and m models will be released after paper accepted and published.

**Comment by SwEngine** [comment]
Thank you so much, nano version is very essential for real time systems.

**Comment by haviduck** [comment]
> Maybe release with s and m models at same time. In our plan, s and m models will be released after paper accepted and published.

exciting! any place i can track the paper and whether or not it has been accepted/published?
