### ISSUE TITLE
GELAN pic wrong?

### ISSUE THREAD

**Issue by Yinjie-ZHENG** [WongKinYiu/yolov9#75]
Dear author,
Thanks for your nice job. Here's my question regarding to GELAN implement:
I see the source code about GELAN, which is located here:

```
class RepNCSPELAN4(nn.Module):
   
    def __init__(self, c1, c2, c3, c4, c5=1): 
        super().__init__()
        self.c = c3//2
        self.cv1 = Conv(c1, c3, 1, 1)
        self.cv2 = nn.Sequential(RepNCSP(c3//2, c4, c5), Conv(c4, c4, 3, 1))
        self.cv3 = nn.Sequential(RepNCSP(c4, c4, c5), Conv(c4, c4, 3, 1))
        self.cv4 = Conv(c3+(2*c4), c2, 1, 1)

    def forward(self, x):
        y = list(self.cv1(x).chunk(2, 1))
        y.extend((m(y[-1])) for m in [self.cv2, self.cv3])
        return self.cv4(torch.cat(y, 1))

    def forward_split(self, x):
        y = list(self.cv1(x).split((self.c, self.c), 1))
        y.extend(m(y[-1]) for m in [self.cv2, self.cv3])
        return self.cv4(torch.cat(y, 1))
```

and I see that in your paper, the GELAN has only concatation from A,C,D,E... Missing tensor from B?
Shall I understand your GELAN like the following screenshot:
![1708931836647](https://github.com/WongKinYiu/yolov9/assets/86654879/50a906af-6319-405c-a3fc-6c212ef3d7c3)

**Comment by WongKinYiu** [comment]
Yes, you are correct.
B will connect to concatenation too.

**Comment by WongKinYiu** [comment]
![image](https://github.com/WongKinYiu/yolov9/assets/12152972/8cca4803-8c16-4601-9c97-981ac73670d6)

fixed.
