### ISSUE TITLE
min_items and close_mosaic parameters

### ISSUE THREAD

**Issue by Egorundel** [WongKinYiu/yolov9#77]
Hello!
What is the role of `--min-items` and `--close-mosaic`? 
What exactly are they responsible for?

**Comment by WongKinYiu** [comment]
min items is used to filter images. https://github.com/WongKinYiu/yolov9/blob/main/utils/dataloaders.py#L510
close mosaic is used to close mosaic data augmentation. https://github.com/WongKinYiu/yolov9/blob/main/train.py#L263
