### ISSUE TITLE
Inference YOLOV9 add nms batched by TensorRT (Python backend)

### ISSUE THREAD

**Issue by thaitc-hust** [WongKinYiu/yolov9#79]
give me star if my repo helpful for you!
link: https://github.com/thaitc-hust/yolov9-tensorrt

**Comment by WongKinYiu** [comment]
added to readme.

**Comment by WongKinYiu** [comment]
https://github.com/thaitc-hust/yolov9-tensorrt/blob/main/torch2onnx.py#L27

you may need use `output = output[1]` instead.

**Comment by laugh12321** [comment]
Hello everyone!

I would like to introduce my open-source project - [TensoRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO), a tool for deploying YOLO Series (Support YOLOv9) with Efficient NMS in TensorRT. 

## Key Features

- Supports FLOAT32, FLOAT16 ONNX export, and TensorRT inference
- Supports YOLOv5, YOLOv8, YOLOv9, PP-YOLOE, and PP-YOLOE+
- Integrates EfficientNMS TensorRT plugin for accelerated post-processing
- Utilizes CUDA kernel functions to accelerate preprocess
- Supports C++ and Python inference

**Comment by zahidzqj** [comment]
> https://github.com/thaitc-hust/yolov9-tensorrt/blob/main/torch2onnx.py#L27
> 
> you may need use `output = output[1]` instead.

I found some differences between the results of Pytorch inference and Tensorrt-NMS inference，but  I don't know how it happened
