### ISSUE TITLE
RepConvN infer & remove the auxiliary head

### ISSUE THREAD

**Issue by violet2422** [WongKinYiu/yolov9#8]
During the inference process, not removing the auxiliary branch will reduce the inference speed. Where is the main code for removing the auxiliary branch; Additionally, it seems that the code does not provide reparameterized code for RepConvN related inference processes

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9?tab=readme-ov-file#re-parameterization

Re-parameterization part is under construction.
