### ISSUE TITLE
Small + Medium Configs

### ISSUE THREAD

**Issue by Pbatch** [WongKinYiu/yolov9#89]
Hello,

Would it be possible to add the small/medium configs to `models/detect/*.yaml`?

I'm excited to see what we can do on edge devices with these new models.

Thanks :)

**Comment by ueke616** [comment]
how to download Small and Medium model? The download connection is unavailable.

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/issues/3#issuecomment-1958745515
