### ISSUE TITLE
Yolov9 inference on C#

### ISSUE THREAD

**Issue by Kayzwer** [WongKinYiu/yolov9#95]
https://github.com/Kayzwer/yolo-cs

**Comment by WongKinYiu** [comment]
Added to readme.

**Comment by Kayzwer** [comment]
@WongKinYiu sorry one more thing, https://github.com/Kayzwer/openvino-yolo-cs this is yolov9 inference on C# with openvino, also there is a pull request that fix openvino export https://github.com/WongKinYiu/yolov9/pull/108

**Comment by WongKinYiu** [comment]
Please check you will get `ElementAt(0)` or `ElementAt(1)`.

For example: https://github.com/Kayzwer/yolo-cs/blob/master/Yolov9.cs#L73

**Comment by Kayzwer** [comment]
> Please check you will get `ElementAt(0)` or `ElementAt(1)`.
> 
> For example: https://github.com/Kayzwer/yolo-cs/blob/master/Yolov9.cs#L73

the code products expected result without any errors.

**Comment by BingGitCn** [comment]
public class Yolov9 : **Yolo** 
where is this  : **Yolo**

**Comment by Kayzwer** [comment]
> public class Yolov9 : **Yolo** where is this : **Yolo**

this fix is done, but let me rerun a test to make sure all the classes are working properly.
