### ISSUE TITLE
YOLOv9 Deploy on Edge AI SoC with AX650N, 38fps.

### ISSUE THREAD

**Issue by BUG1989** [WongKinYiu/yolov9#96]
Hi, we have deployed YOLOv9-C on our AI SoC，AX650N(10.8TOPs@Int8)

- https://github.com/AXERA-TECH/ax-samples/tree/main/examples/ax650#YOLOv9
- https://zhuanlan.zhihu.com/p/683622844

**Comment by WongKinYiu** [comment]
Thanks, added to readme.
